export interface Language {
  code: string;
  name: string;
  flag: string;
  greeting: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', greeting: 'Welcome' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', greeting: 'مرحباً' },
  { code: 'es', name: 'Español', flag: '🇪🇸', greeting: 'Bienvenido' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', greeting: 'Bienvenue' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', greeting: 'Willkommen' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹', greeting: 'Benvenuto' },
  { code: 'pt', name: 'Português', flag: '🇧🇷', greeting: 'Bem-vindo' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', greeting: 'Добро пожаловать' },
  { code: 'zh', name: '中文', flag: '🇨🇳', greeting: '欢迎' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', greeting: 'ようこそ' },
  { code: 'ko', name: '한국어', flag: '🇰🇷', greeting: '환영합니다' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', greeting: 'स्वागत है' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷', greeting: 'Hoş geldiniz' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱', greeting: 'Welkom' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪', greeting: 'Välkommen' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰', greeting: 'Velkommen' },
  { code: 'no', name: 'Norsk', flag: '🇳🇴', greeting: 'Velkommen' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮', greeting: 'Tervetuloa' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱', greeting: 'Witamy' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿', greeting: 'Vítejte' },
  { code: 'sk', name: 'Slovenčina', flag: '🇸🇰', greeting: 'Vitajte' },
  { code: 'hu', name: 'Magyar', flag: '🇭🇺', greeting: 'Üdvözöljük' },
  { code: 'ro', name: 'Română', flag: '🇷🇴', greeting: 'Bun venit' },
  { code: 'bg', name: 'Български', flag: '🇧🇬', greeting: 'Добре дошли' },
  { code: 'hr', name: 'Hrvatski', flag: '🇭🇷', greeting: 'Dobrodošli' },
  { code: 'sr', name: 'Српски', flag: '🇷🇸', greeting: 'Добродошли' },
  { code: 'sl', name: 'Slovenščina', flag: '🇸🇮', greeting: 'Dobrodošli' },
  { code: 'et', name: 'Eesti', flag: '🇪🇪', greeting: 'Tere tulemast' },
  { code: 'lv', name: 'Latviešu', flag: '🇱🇻', greeting: 'Laipni lūdzam' },
  { code: 'lt', name: 'Lietuvių', flag: '🇱🇹', greeting: 'Sveiki atvykę' },
  { code: 'mt', name: 'Malti', flag: '🇲🇹', greeting: 'Merħba' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷', greeting: 'Καλώς ήρθατε' },
  { code: 'cy', name: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', greeting: 'Croeso' },
  { code: 'ga', name: 'Gaeilge', flag: '🇮🇪', greeting: 'Fáilte' },
  { code: 'is', name: 'Íslenska', flag: '🇮🇸', greeting: 'Velkomin' },
  { code: 'mk', name: 'Македонски', flag: '🇲🇰', greeting: 'Добредојдовте' },
  { code: 'sq', name: 'Shqip', flag: '🇦🇱', greeting: 'Mirë se vini' },
  { code: 'eu', name: 'Euskera', flag: '🇪🇸', greeting: 'Ongi etorri' },
  { code: 'ca', name: 'Català', flag: '🇪🇸', greeting: 'Benvingut' },
  { code: 'gl', name: 'Galego', flag: '🇪🇸', greeting: 'Benvido' },
  { code: 'he', name: 'עברית', flag: '🇮🇱', greeting: 'ברוכים הבאים' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭', greeting: 'ยินดีต้อนรับ' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳', greeting: 'Chào mừng' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩', greeting: 'Selamat datang' },
  { code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾', greeting: 'Selamat datang' },
  { code: 'tl', name: 'Filipino', flag: '🇵🇭', greeting: 'Maligayang pagdating' },
  { code: 'sw', name: 'Kiswahili', flag: '🇰🇪', greeting: 'Karibu' },
  { code: 'am', name: 'አማርኛ', flag: '🇪🇹', greeting: 'እንኳን ደህና መጡ' },
  { code: 'yo', name: 'Yorùbá', flag: '🇳🇬', greeting: 'Ẹ kú àbọ̀' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬', greeting: 'Nnọọ' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬', greeting: 'Barka da zuwa' },
  { code: 'zu', name: 'isiZulu', flag: '🇿🇦', greeting: 'Sawubona' },
  { code: 'xh', name: 'isiXhosa', flag: '🇿🇦', greeting: 'Wamkelekile' },
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦', greeting: 'Welkom' },
  { code: 'ur', name: 'اردو', flag: '🇵🇰', greeting: 'خوش آمدید' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩', greeting: 'স্বাগতম' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳', greeting: 'ਜੀ ਆਇਆਂ ਨੂੰ' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳', greeting: 'સ્વાગત છે' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳', greeting: 'வரவேற்கிறோம்' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳', greeting: 'స్వాగతం' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳', greeting: 'ಸ್ವಾಗತ' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳', greeting: 'സ്വാഗതം' },
  { code: 'or', name: 'ଓଡ଼ିଆ', flag: '🇮🇳', greeting: 'ସ୍ୱାଗତ' },
  { code: 'as', name: 'অসমীয়া', flag: '🇮🇳', greeting: 'স্বাগতম' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳', greeting: 'स्वागत आहे' },
  { code: 'ne', name: 'नेपाली', flag: '🇳🇵', greeting: 'स्वागतम्' },
  { code: 'si', name: 'සිංහල', flag: '🇱🇰', greeting: 'ආයුබෝවන්' },
  { code: 'my', name: 'မြန်မာ', flag: '🇲🇲', greeting: 'ကြိုဆိုပါတယ်' },
  { code: 'km', name: 'ខ្មែរ', flag: '🇰🇭', greeting: 'សូមស្វាគមន៍' },
  { code: 'lo', name: 'ລາວ', flag: '🇱🇦', greeting: 'ຍິນດີຕ້ອນຮັບ' },
  { code: 'ka', name: 'ქართული', flag: '🇬🇪', greeting: 'კეთილი იყოს თქვენი მობრძანება' },
  { code: 'hy', name: 'Հայերեն', flag: '🇦🇲', greeting: 'Բարի գալուստ' },
  { code: 'az', name: 'Azərbaycan', flag: '🇦🇿', greeting: 'Xoş gəldiniz' },
  { code: 'kk', name: 'Қазақша', flag: '🇰🇿', greeting: 'Қош келдіңіздер' },
  { code: 'ky', name: 'Кыргызча', flag: '🇰🇬', greeting: 'Кош келдиңиздер' },
  { code: 'uz', name: 'O\'zbek', flag: '🇺🇿', greeting: 'Xush kelibsiz' },
  { code: 'tj', name: 'Тоҷикӣ', flag: '🇹🇯', greeting: 'Хуш омадед' },
  { code: 'tk', name: 'Türkmen', flag: '🇹🇲', greeting: 'Hoş geldiňiz' },
  { code: 'mn', name: 'Монгол', flag: '🇲🇳', greeting: 'Тавтай морилно уу' },
  { code: 'bo', name: 'བོད་ཡིག', flag: '🇨🇳', greeting: 'བཀྲིས་བདེ་ལེགས་' },
  { code: 'ug', name: 'ئۇيغۇرچە', flag: '🇨🇳', greeting: 'مەرھابا' },
  { code: 'fa', name: 'فارسی', flag: '🇮🇷', greeting: 'خوش آمدید' },
  { code: 'ps', name: 'پښتو', flag: '🇦🇫', greeting: 'ښه راغلاست' },
  { code: 'ku', name: 'Kurdî', flag: '🇹🇷', greeting: 'Bi xêr hatin' }
];

const TRANSLATIONS = {
  // Common
  friends: {
    en: 'Friends',
    ar: 'الأصدقاء',
    es: 'Amigos',
    fr: 'Amis',
    de: 'Freunde',
    it: 'Amici',
    pt: 'Amigos',
    ru: 'Друзья',
    zh: '朋友',
    ja: '友達',
    ko: '친구들',
    hi: 'मित्र',
    tr: 'Arkadaşlar',
    nl: 'Vrienden',
    sv: 'Vänner',
    da: 'Venner',
    no: 'Venner',
    fi: 'Ystävät',
    pl: 'Przyjaciele',
    cs: 'Přátelé',
    sk: 'Priatelia',
    hu: 'Barátok',
    ro: 'Prieteni',
    bg: 'Приятели',
    hr: 'Prijatelji',
    sr: 'Пријатељи',
    sl: 'Prijatelji',
    et: 'Sõbrad',
    lv: 'Draugi',
    lt: 'Draugai',
    mt: 'Ħbieb',
    el: 'Φίλοι',
    cy: 'Ffrindiau',
    ga: 'Cairde',
    is: 'Vinir',
    mk: 'Пријатели',
    sq: 'Miq',
    eu: 'Lagunak',
    ca: 'Amics',
    gl: 'Amigos',
    he: 'חברים',
    th: 'เพื่อน',
    vi: 'Bạn bè',
    id: 'Teman',
    ms: 'Kawan',
    tl: 'Mga Kaibigan',
    sw: 'Marafiki',
    am: 'ጓደኞች',
    yo: 'Àwọn ọ̀rẹ́',
    ig: 'Ndị enyi',
    ha: 'Abokai',
    zu: 'Abangane',
    xh: 'Abahlobo',
    af: 'Vriende',
    ur: 'دوست',
    bn: 'বন্ধুরা',
    pa: 'ਮਿੱਤਰ',
    gu: 'મિત્રો',
    ta: 'நண்பர்கள்',
    te: 'స్నేహితులు',
    kn: 'ಸ್ನೇಹಿತರು',
    ml: 'സുഹൃത്തുക്കൾ',
    or: 'ବନ୍ଧୁମାନେ',
    as: 'বন্ধুসকল',
    mr: 'मित्र',
    ne: 'साथीहरू',
    si: 'මිතුරන්',
    my: 'မိတ်ဆွေများ',
    km: 'មិត្តភក្តិ',
    lo: 'ໝູ່',
    ka: 'მეგობრები',
    hy: 'Ընկերներ',
    az: 'Dostlar',
    kk: 'Достар',
    ky: 'Досторо',
    uz: 'Do\'stlar',
    tj: 'Дӯстон',
    tk: 'Dostlar',
    mn: 'Найзууд',
    bo: 'གྲོགས་པོ',
    ug: 'دوستلار',
    fa: 'دوستان',
    ps: 'ملګري',
    ku: 'Heval'
  },
  inviteFriendsEarn: {
    en: 'Invite friends and earn $SPACE coins together',
    ar: 'ادع الأصدقاء واكسب عملات $SPACE معًا',
    es: 'Invita amigos y gana monedas $SPACE juntos',
    fr: 'Invitez des amis et gagnez des pièces $SPACE ensemble',
    de: 'Lade Freunde ein und verdiene $SPACE-Münzen zusammen',
    it: 'Invita amici e guadagna monete $SPACE insieme',
    pt: 'Convide amigos e ganhe moedas $SPACE juntos',
    ru: 'Приглашайте друзей и зарабатывайте монеты $SPACE вместе',
    zh: '邀请朋友一起赚取$SPACE币',
    ja: '友達を招待して一緒に$SPACEコインを稼ごう',
    ko: '친구들을 초대하고 함께 $SPACE 코인을 얻으세요',
    hi: 'मित्रों को आमंत्रित करें और $SPACE सिक्के साथ कमाएं',
    tr: 'Arkadaşlarını davet et ve birlikte $SPACE coin kazan',
    nl: 'Nodig vrienden uit en verdien samen $SPACE munten',
    sv: 'Bjud in vänner och tjäna $SPACE mynt tillsammans',
    da: 'Inviter venner og tjen $SPACE mønter sammen',
    no: 'Inviter venner og tjen $SPACE mynter sammen',
    fi: 'Kutsu ystäviä ja ansaitse $SPACE kolikoita yhdessä',
    pl: 'Zapraszaj przyjaciół i zarabiaj monety $SPACE razem',
    cs: 'Pozvěte přátele a vydělávejte mince $SPACE společně',
    sk: 'Pozvite priateľov a zarábajte mince $SPACE spoločne',
    hu: 'Hívj barátokat és keress $SPACE érméket együtt',
    ro: 'Invită prieteni și câștigă monede $SPACE împreună',
    bg: 'Поканете приятели и печелете $SPACE монети заедно',
    hr: 'Pozovite prijatelje i zaradite $SPACE kovanice zajedno',
    sr: 'Позовите пријатеље и зарадите $SPACE новчиће заједно',
    sl: 'Povabite prijatelje in skupaj zaslužite $SPACE kovance',
    et: 'Kutsu sõpru ja teenige $SPACE münte koos',
    lv: 'Uzaiciniet draugus un kopā nopelniet $SPACE monētas',
    lt: 'Pakvieskite draugus ir kartu uždirbkite $SPACE monetų',
    mt: 'Istieden lil ħbieb u aqilgħu muniti $SPACE flimkien',
    el: 'Προσκαλέστε φίλους και κερδίστε νομίσματα $SPACE μαζί',
    cy: 'Gwahoddwch ffrindiau ac ennill darnau arian $SPACE gyda\'ch gilydd',
    ga: 'Tabhair cuireadh do chairde agus tuilleamh boinn $SPACE le chéile',
    is: 'Bjóddu vinum og vinndu $SPACE mynt saman',
    mk: 'Поканете пријатели и заработете $SPACE монети заедно',
    sq: 'Ftoni miq dhe fitoni monedha $SPACE së bashku',
    eu: 'Gonbidatu lagunak eta irabazi $SPACE txanponak elkarrekin',
    ca: 'Convida amics i guanya monedes $SPACE junts',
    gl: 'Convida amigos e gaña moedas $SPACE xuntos',
    he: 'הזמן חברים וזכה במטבעות $SPACE יחד',
    th: 'เชิญเพื่อนและหาเหรียญ $SPACE ด้วยกัน',
    vi: 'Mời bạn bè và kiếm xu $SPACE cùng nhau',
    id: 'Undang teman dan dapatkan koin $SPACE bersama',
    ms: 'Jemput kawan dan perolehi syiling $SPACE bersama',
    tl: 'Mag-imbita ng mga kaibigan at kumita ng mga barya ng $SPACE nang sama-sama',
    sw: 'Alika marafiki na upate sarafu za $SPACE pamoja',
    am: 'ጓደኞችን ጋብዝና $SPACE ሳንቲሞችን አብራችሁ አግኙ',
    yo: 'Pe àwọn ọ̀rẹ́ kí ẹ sì jọ gba owó $SPACE',
    ig: 'Kpọọ ndị enyi ka unu nwetakọọ mkpụrụ ego $SPACE',
    ha: 'Kira abokai ku karɓi kuɗin $SPACE tare',
    zu: 'Mema abangane futhi nizuze izinhlamvu zemali ze-$SPACE ndawonye',
    xh: 'Memela abahlobo futhi nifumane iingqekembe ze$SPACE kunye',
    af: 'Nooi vriende en verdien $SPACE munte saam',
    ur: 'دوستوں کو مدعو کریں اور $SPACE سکے حاصل کریں',
    bn: 'বন্ধুদের আমন্ত্রণ জানান এবং একসাথে $SPACE কয়েন অর্জন করুন',
    pa: 'ਦੋਸਤਾਂ ਨੂੰ ਸੱਦਾ ਦਿਓ ਅਤੇ ਮਿਲ ਕੇ $SPACE ਸਿੱਕੇ ਕਮਾਓ',
    gu: 'મિત્રોને આમંત્રણ આપો અને એકસાથે $SPACE સિક્કા કમાઓ',
    ta: 'நண்பர்களை அழைத்து ஒன்றாக $SPACE நாணயங்களை சம்பாதிக்கவும்',
    te: 'స్నేహితులను ఆహ్వానించి కలిసి $SPACE నాణేలు సంపాదించండి',
    kn: 'ಸ್ನೇಹಿತರನ್ನು ಆಹ್ವಾನಿಸಿ ಮತ್ತು ಒಟ್ಟಾಗಿ $SPACE ನಾಣ್ಯಗಳನ್ನು ಗಳಿಸಿ',
    ml: 'സുഹൃത്തുക്കളെ ക്ഷണിച്ച് ഒരുമിച്ച് $SPACE നാണയങ്ങൾ സമ്പാദിക്കൂ',
    or: 'ବନ୍ଧୁମାନଙ୍କୁ ଆମନ୍ତ୍ରଣ କରନ୍ତୁ ଏବଂ ଏକସାଥେ $SPACE ମୁଦ୍ରା ଅର୍ଜନ କରନ୍ତୁ',
    as: 'বন্ধুসকলক আমন্ত্ৰণ কৰক আৰু একেলগে $SPACE মুদ্ৰা অৰ্জন কৰক',
    mr: 'मित्रांना आमंत्रित करा आणि एकत्र $SPACE नाणी मिळवा',
    ne: 'साथीहरूलाई निमन्त्रणा दिनुहोस् र सँगै $SPACE सिक्काहरू कमाउनुहोस्',
    si: 'මිතුරන්ට ආරාධනා කර එකට $SPACE කාසි උපයන්න',
    my: 'မိတ်ဆွေများကို ဖိတ်ကြား၍ $SPACE အကြွေများကို အတူရယူပါ',
    km: 'អញ្ជើញមិត្តភក្តិ និងរកប្រាក់ $SPACE ជាមួយគ្នា',
    lo: 'ເຊີນໝູ່ແລະຫາເງິນ $SPACE ຮ່ວມກັນ',
    ka: 'მოიწვიეთ მეგობრები და ერთად მოიგეთ $SPACE მონეტები',
    hy: 'Հրավիրեք ընկերներին և համատեղ վաստակեք $SPACE մետաղադրամներ',
    az: 'Dostları dəvət edin və birlikdə $SPACE sikkələri qazanın',
    kk: 'Достарды шақырып, бірге $SPACE монеталарын табыңыз',
    ky: 'Досторго чакырып, чогуу $SPACE тыйындарды табыңыз',
    uz: 'Do\'stlarni taklif qiling va birgalikda $SPACE tangalarini ishlang',
    tj: 'Дӯстонро даъват кунед ва якҷоя тангаҳои $SPACE ба даст оред',
    tk: 'Dostlary çagyryň we bile $SPACE teňňelerini gazanyň',
    mn: 'Найзуудаа урьж хамтдаа $SPACE зоосыг олцгооё',
    bo: 'གྲོགས་པོ་རྣམས་སྤྱན་འདྲེན་བྱས་ནས་མཉམ་དུ་$SPACE་སྒོར་མོ་རེད',
    ug: 'دوستلارنى تەكلىپ قىلىپ بىرلىكتە $SPACE تەڭگىلەرنى ئېلىڭ',
    fa: 'دوستان را دعوت کنید و با هم سکه‌های $SPACE بدست آورید',
    ps: 'ملګري بلنه کړئ او په ګډه د $SPACE سکې وګټئ',
    ku: 'Hevaletî vexwe û bi hev re dravên $SPACE bidest bixin'
  },
  getReferralLink: {
    en: 'Get Your Referral Link',
    ar: 'احصل على رابط الإحالة الخاص بك',
    es: 'Obtén tu enlace de referido',
    fr: 'Obtenez votre lien de parrainage',
    de: 'Holen Sie sich Ihren Empfehlungslink',
    it: 'Ottieni il tuo link di referral',
    pt: 'Obtenha seu link de indicação',
    ru: 'Получите свою реферальную ссылку',
    zh: '获取您的推荐链接',
    ja: '紹介リンクを取得',
    ko: '추천 링크를 받으세요',
    hi: 'अपना रेफरल लिंक प्राप्त करें',
    tr: 'Yönlendirme bağlantınızı alın'
  },
  goToBot: {
    en: 'Go to',
    ar: 'اذهب إلى',
    es: 'Ve a',
    fr: 'Allez à',
    de: 'Gehe zu',
    it: 'Vai a',
    pt: 'Vá para',
    ru: 'Перейти к',
    zh: '前往',
    ja: 'に移動',
    ko: '이동',
    hi: 'जाएं',
    tr: 'Git'
  },
  onTelegram: {
    en: 'on Telegram',
    ar: 'على التليجرام',
    es: 'en Telegram',
    fr: 'sur Telegram',
    de: 'auf Telegram',
    it: 'su Telegram',
    pt: 'no Telegram',
    ru: 'в Telegram',
    zh: '在Telegram上',
    ja: 'Telegramで',
    ko: 'Telegram에서',
    hi: 'टेलीग्राम पर',
    tr: 'Telegram\'da'
  },
  sendCommand: {
    en: 'Send the command',
    ar: 'أرسل الأمر',
    es: 'Envía el comando',
    fr: 'Envoyez la commande',
    de: 'Senden Sie den Befehl',
    it: 'Invia il comando',
    pt: 'Envie o comando',
    ru: 'Отправьте команду',
    zh: '发送命令',
    ja: 'コマンドを送信',
    ko: '명령어를 보내세요',
    hi: 'कमांड भेजें',
    tr: 'Komutu gönder'
  },
  receiveLink: {
    en: 'You will receive your personal referral link',
    ar: 'ستحصل على رابط الإحالة الشخصي الخاص بك',
    es: 'Recibirás tu enlace de referido personal',
    fr: 'Vous recevrez votre lien de parrainage personnel',
    de: 'Sie erhalten Ihren persönlichen Empfehlungslink',
    it: 'Riceverai il tuo link di referral personale',
    pt: 'Você receberá seu link de indicação pessoal',
    ru: 'Вы получите вашу личную реферальную ссылку',
    zh: '您将收到个人推荐链接',
    ja: '個人の紹介リンクを受け取ります',
    ko: '개인 추천 링크를 받게 됩니다',
    hi: 'आपको अपना व्यक्तिगत रेफरल लिंक मिलेगा',
    tr: 'Kişisel yönlendirme bağlantınızı alacaksınız'
  },
  openBot: {
    en: 'Open @Spacelbot',
    ar: 'افتح @Spacelbot',
    es: 'Abrir @Spacelbot',
    fr: 'Ouvrir @Spacelbot',
    de: '@Spacelbot öffnen',
    it: 'Apri @Spacelbot',
    pt: 'Abrir @Spacelbot',
    ru: 'Открыть @Spacelbot',
    zh: '打开 @Spacelbot',
    ja: '@Spacelbotを開く',
    ko: '@Spacelbot 열기',
    hi: '@Spacelbot खोलें',
    tr: '@Spacelbot\'u aç'
  },
  // Wallet Page
  smartWallet: {
    en: 'Smart Wallet',
    ar: 'المحفظة الذكية',
    es: 'Billetera Inteligente',
    fr: 'Portefeuille Intelligent',
    de: 'Smart Wallet',
    it: 'Portafoglio Intelligente',
    pt: 'Carteira Inteligente',
    ru: 'Умный кошелек',
    zh: '智能钱包',
    ja: 'スマートウォレット',
    ko: '스마트 지갑',
    hi: 'स्मार्ट वॉलेट',
    tr: 'Akıllı Cüzdan'
  },
  walletDescription: {
    en: 'Secure storage and management of your $SPACE and TON tokens',
    ar: 'التخزين الآمن وإدارة رموز $SPACE و TON الخاصة بك',
    es: 'Almacenamiento seguro y gestión de tus tokens $SPACE y TON',
    fr: 'Stockage sécurisé et gestion de vos tokens $SPACE et TON',
    de: 'Sichere Aufbewahrung und Verwaltung Ihrer $SPACE- und TON-Token',
    it: 'Archiviazione sicura e gestione dei tuoi token $SPACE e TON',
    pt: 'Armazenamento seguro e gerenciamento de seus tokens $SPACE e TON',
    ru: 'Безопасное хранение и управление вашими токенами $SPACE и TON',
    zh: '安全存储和管理您的$SPACE和TON代币',
    ja: '$SPACEとTONトークンの安全な保管と管理',
    ko: '$SPACE 및 TON 토큰의 안전한 저장 및 관리',
    hi: 'आपके $SPACE और TON टोकन का सुरक्षित भंडारण और प्रबंधन',
    tr: '$SPACE ve TON tokenlarınızın güvenli saklanması ve yönetimi'
  },
  connectWallet: {
    en: 'Connect Wallet',
    ar: 'ربط المحفظة',
    es: 'Conectar Billetera',
    fr: 'Connecter le Portefeuille',
    de: 'Wallet verbinden',
    it: 'Connetti Portafoglio',
    pt: 'Conectar Carteira',
    ru: 'Подключить кошелек',
    zh: '连接钱包',
    ja: 'ウォレットを接続',
    ko: '지갑 연결',
    hi: 'वॉलेट कनेक्ट करें',
    tr: 'Cüzdan Bağla'
  },
  connectWalletToAccess: {
    en: 'Connect your TON wallet to access all features',
    ar: 'اربط محفظة TON للوصول إلى جميع الميزات',
    es: 'Conecta tu billetera TON para acceder a todas las funciones',
    fr: 'Connectez votre portefeuille TON pour accéder à toutes les fonctionnalités',
    de: 'Verbinden Sie Ihr TON-Wallet, um auf alle Funktionen zuzugreifen',
    it: 'Connetti il tuo portafoglio TON per accedere a tutte le funzionalità',
    pt: 'Conecte sua carteira TON para acessar todos os recursos',
    ru: 'Подключите свой кошелек TON для доступа ко всем функциям',
    zh: '连接您的TON钱包以访问所有功能',
    ja: 'すべての機能にアクセスするためにTONウォレットを接続してください',
    ko: '모든 기능에 액세스하려면 TON 지갑을 연결하세요',
    hi: 'सभी सुविधाओं तक पहुंचने के लिए अपना TON वॉलेट कनेक्ट करें',
    tr: 'Tüm özelliklere erişmek için TON cüzdanınızı bağlayın'
  },
  connecting: {
    en: 'Connecting...',
    ar: 'جاري الاتصال...',
    es: 'Conectando...',
    fr: 'Connexion...',
    de: 'Verbinden...',
    it: 'Connessione...',
    pt: 'Conectando...',
    ru: 'Подключение...',
    zh: '连接中...',
    ja: '接続中...',
    ko: '연결 중...',
    hi: 'कनेक्ट हो रहा है...',
    tr: 'Bağlanıyor...'
  },
  walletConnected: {
    en: 'Wallet Connected',
    ar: 'المحفظة متصلة',
    es: 'Billetera Conectada',
    fr: 'Portefeuille Connecté',
    de: 'Wallet verbunden',
    it: 'Portafoglio Connesso',
    pt: 'Carteira Conectada',
    ru: 'Кошелек подключен',
    zh: '钱包已连接',
    ja: 'ウォレット接続済み',
    ko: '지갑 연결됨',
    hi: 'वॉलेट कनेक्ट हो गया',
    tr: 'Cüzdan Bağlandı'
  },
  disconnectWallet: {
    en: 'Disconnect',
    ar: 'قطع الاتصال',
    es: 'Desconectar',
    fr: 'Déconnecter',
    de: 'Trennen',
    it: 'Disconnetti',
    pt: 'Desconectar',
    ru: 'Отключить',
    zh: '断开连接',
    ja: '切断',
    ko: '연결 해제',
    hi: 'डिस्कनेक्ट करें',
    tr: 'Bağlantıyı Kes'
  },
  mainCurrency: {
    en: 'Main Currency',
    ar: 'العملة الرئيسية',
    es: 'Moneda Principal',
    fr: 'Devise Principale',
    de: 'Hauptwährung',
    it: 'Valuta Principale',
    pt: 'Moeda Principal',
    ru: 'Основная валюта',
    zh: '主要货币',
    ja: 'メイン通貨',
    ko: '주요 통화',
    hi: 'मुख्य मुद्रा',
    tr: 'Ana Para Birimi'
  },
  walletAddress: {
    en: 'Wallet Address',
    ar: 'عنوان المحفظة',
    es: 'Dirección de Billetera',
    fr: 'Adresse du Portefeuille',
    de: 'Wallet-Adresse',
    it: 'Indirizzo Portafoglio',
    pt: 'Endereço da Carteira',
    ru: 'Адрес кошелька',
    zh: '钱包地址',
    ja: 'ウォレットアドレス',
    ko: '지갑 주소',
    hi: 'वॉलेट पता',
    tr: 'Cüzdan Adresi'
  },
  latestTransactions: {
    en: 'Latest Transactions',
    ar: 'أحدث المعاملات',
    es: 'Últimas Transacciones',
    fr: 'Dernières Transactions',
    de: 'Neueste Transaktionen',
    it: 'Ultime Transazioni',
    pt: 'Últimas Transações',
    ru: 'Последние транзакции',
    zh: '最近交易',
    ja: '最新の取引',
    ko: '최근 거래',
    hi: 'नवीनतम लेनदेन',
    tr: 'Son İşlemler'
  },
  loadingTransactions: {
    en: 'Loading transactions...',
    ar: 'جاري تحميل المعاملات...',
    es: 'Cargando transacciones...',
    fr: 'Chargement des transactions...',
    de: 'Transaktionen laden...',
    it: 'Caricamento transazioni...',
    pt: 'Carregando transações...',
    ru: 'Загрузка транзакций...',
    zh: '加载交易中...',
    ja: '取引を読み込み中...',
    ko: '거래 로딩 중...',
    hi: 'लेनदेन लोड हो रहे हैं...',
    tr: 'İşlemler yükleniyor...'
  },
  noTransactions: {
    en: 'No Transactions Yet',
    ar: 'لا توجد معاملات بعد',
    es: 'Aún No Hay Transacciones',
    fr: 'Aucune Transaction Encore',
    de: 'Noch keine Transaktionen',
    it: 'Nessuna Transazione Ancora',
    pt: 'Nenhuma Transação Ainda',
    ru: 'Пока нет транзакций',
    zh: '暂无交易',
    ja: 'まだ取引がありません',
    ko: '아직 거래가 없습니다',
    hi: 'अभी तक कोई लेनदेन नहीं',
    tr: 'Henüz İşlem Yok'
  },
  startSendingReceiving: {
    en: 'Start sending and receiving to see your activity here',
    ar: 'ابدأ في الإرسال والاستقبال لرؤية نشاطك هنا',
    es: 'Comience a enviar y recibir para ver su actividad aquí',
    fr: 'Commencez à envoyer et recevoir pour voir votre activité ici',
    de: 'Beginnen Sie mit dem Senden und Empfangen, um Ihre Aktivität hier zu sehen',
    it: 'Inizia a inviare e ricevere per vedere la tua attività qui',
    pt: 'Comece a enviar e receber para ver sua atividade aqui',
    ru: 'Начните отправлять и получать, чтобы увидеть свою активность здесь',
    zh: '开始发送和接收以查看您的活动',
    ja: '送信と受信を開始して、ここでアクティビティを確認してください',
    ko: '여기서 활동을 보려면 송금 및 수신을 시작하세요',
    hi: 'यहाँ अपनी गतिविधि देखने के लिए भेजना और प्राप्त करना शुरू करें',
    tr: 'Etkinliğinizi burada görmek için gönderme ve alma işlemlerine başlayın'
  },
  // Toast messages
  openConnectionWindow: {
    en: 'Opening connection window',
    ar: 'فتح نافذة الاتصال',
    es: 'Abriendo ventana de conexión',
    fr: 'Ouverture de la fenêtre de connexion',
    de: 'Verbindungsfenster öffnen',
    it: 'Apertura finestra di connessione',
    pt: 'Abrindo janela de conexão',
    ru: 'Открытие окна подключения',
    zh: '打开连接窗口',
    ja: '接続ウィンドウを開いています',
    ko: '연결 창 열기',
    hi: 'कनेक्शन विंडो खोली जा रही है',
    tr: 'Bağlantı penceresi açılıyor'
  },
  pleaseSelectWallet: {
    en: 'Please select your wallet from the list',
    ar: 'يرجى اختيار محفظتك من القائمة',
    es: 'Por favor seleccione su billetera de la lista',
    fr: 'Veuillez sélectionner votre portefeuille dans la liste',
    de: 'Bitte wählen Sie Ihr Wallet aus der Liste',
    it: 'Si prega di selezionare il portafoglio dall\'elenco',
    pt: 'Por favor, selecione sua carteira da lista',
    ru: 'Пожалуйста, выберите свой кошелек из списка',
    zh: '请从列表中选择您的钱包',
    ja: 'リストからウォレットを選択してください',
    ko: '목록에서 지갑을 선택해주세요',
    hi: 'कृपया सूची से अपना वॉलेट चुनें',
    tr: 'Lütfen listeden cüzdanınızı seçin'
  },
  connectionError: {
    en: 'Connection Error',
    ar: 'خطأ في الاتصال',
    es: 'Error de Conexión',
    fr: 'Erreur de Connexion',
    de: 'Verbindungsfehler',
    it: 'Errore di Connessione',
    pt: 'Erro de Conexão',
    ru: 'Ошибка подключения',
    zh: '连接错误',
    ja: '接続エラー',
    ko: '연결 오류',
    hi: 'कनेक्शन त्रुटि',
    tr: 'Bağlantı Hatası'
  },
  failedToOpenWallet: {
    en: 'Failed to open wallet connection',
    ar: 'فشل في فتح اتصال المحفظة',
    es: 'Error al abrir la conexión de billetera',
    fr: 'Échec de l\'ouverture de la connexion du portefeuille',
    de: 'Fehler beim Öffnen der Wallet-Verbindung',
    it: 'Impossibile aprire la connessione del portafoglio',
    pt: 'Falha ao abrir conexão da carteira',
    ru: 'Не удалось открыть подключение кошелька',
    zh: '无法打开钱包连接',
    ja: 'ウォレット接続の開始に失敗しました',
    ko: '지갑 연결을 열지 못했습니다',
    hi: 'वॉलेट कनेक्शन खोलने में विफल',
    tr: 'Cüzdan bağlantısı açılamadı'
  },
  disconnected: {
    en: 'Disconnected',
    ar: 'منقطع',
    es: 'Desconectado',
    fr: 'Déconnecté',
    de: 'Getrennt',
    it: 'Disconnesso',
    pt: 'Desconectado',
    ru: 'Отключено',
    zh: '已断开连接',
    ja: '切断されました',
    ko: '연결 해제됨',
    hi: 'डिस्कनेक्ट हो गया',
    tr: 'Bağlantı Kesildi'
  },
  tonWalletDisconnected: {
    en: 'TON wallet has been disconnected',
    ar: 'تم قطع اتصال محفظة TON',
    es: 'La billetera TON ha sido desconectada',
    fr: 'Le portefeuille TON a été déconnecté',
    de: 'TON-Wallet wurde getrennt',
    it: 'Il portafoglio TON è stato disconnesso',
    pt: 'A carteira TON foi desconectada',
    ru: 'Кошелек TON был отключен',
    zh: 'TON钱包已断开连接',
    ja: 'TONウォレットが切断されました',
    ko: 'TON 지갑 연결이 해제되었습니다',
    hi: 'TON वॉलेट डिस्कनेक्ट हो गया है',
    tr: 'TON cüzdanı bağlantısı kesildi'
  },
  loadingDataError: {
    en: 'Loading Data Error',
    ar: 'خطأ في تحميل البيانات',
    es: 'Error al Cargar Datos',
    fr: 'Erreur de Chargement des Données',
    de: 'Fehler beim Laden der Daten',
    it: 'Errore di Caricamento Dati',
    pt: 'Erro ao Carregar Dados',
    ru: 'Ошибка загрузки данных',
    zh: '数据加载错误',
    ja: 'データ読み込みエラー',
    ko: '데이터 로딩 오류',
    hi: 'डेटा लोडिंग त्रुटि',
    tr: 'Veri Yükleme Hatası'
  },
  failedToLoadWallet: {
    en: 'Failed to load wallet data',
    ar: 'فشل في تحميل بيانات المحفظة',
    es: 'Error al cargar datos de billetera',
    fr: 'Échec du chargement des données du portefeuille',
    de: 'Fehler beim Laden der Wallet-Daten',
    it: 'Impossibile caricare i dati del portafoglio',
    pt: 'Falha ao carregar dados da carteira',
    ru: 'Не удалось загрузить данные кошелька',
    zh: '无法加载钱包数据',
    ja: 'ウォレットデータの読み込みに失敗しました',
    ko: '지갑 데이터를 로드하지 못했습니다',
    hi: 'वॉलेट डेटा लोड करने में विफल',
    tr: 'Cüzdan verileri yüklenemedi'
  },
  copied: {
    en: 'Copied!',
    ar: 'تم النسخ!',
    es: '¡Copiado!',
    fr: 'Copié!',
    de: 'Kopiert!',
    it: 'Copiato!',
    pt: 'Copiado!',
    ru: 'Скопировано!',
    zh: '已复制！',
    ja: 'コピー済み！',
    ko: '복사됨!',
    hi: 'कॉपी हो गया!',
    tr: 'Kopyalandı!'
  },
  walletAddressCopied: {
    en: 'Wallet address copied to clipboard',
    ar: 'تم نسخ عنوان المحفظة إلى الحافظة',
    es: 'Dirección de billetera copiada al portapapeles',
    fr: 'Adresse du portefeuille copiée dans le presse-papiers',
    de: 'Wallet-Adresse in die Zwischenablage kopiert',
    it: 'Indirizzo portafoglio copiato negli appunti',
    pt: 'Endereço da carteira copiado para a área de transferência',
    ru: 'Адрес кошелька скопирован в буфер обмена',
    zh: '钱包地址已复制到剪贴板',
    ja: 'ウォレットアドレスがクリップボードにコピーされました',
    ko: '지갑 주소가 클립보드에 복사되었습니다',
    hi: 'वॉलेट पता क्लिपबोर्ड पर कॉपी हो गया',
    tr: 'Cüzdan adresi panoya kopyalandı'
  }
};

export const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem('selectedLanguage');
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      const found = SUPPORTED_LANGUAGES.find(lang => lang.code === parsed.code);
      if (found) return found;
    } catch (e) {
      console.warn('Failed to parse stored language:', e);
    }
  }
  return SUPPORTED_LANGUAGES[0]; // Default to English
};

export const setStoredLanguage = (language: Language): void => {
  localStorage.setItem('selectedLanguage', JSON.stringify(language));
};

export const getTranslation = (key: string, languageCode: string): string => {
  const translation = TRANSLATIONS[key as keyof typeof TRANSLATIONS];
  if (!translation) {
    console.warn(`Translation key "${key}" not found`);
    return key;
  }
  
  return translation[languageCode as keyof typeof translation] || translation.en || key;
};

export const detectLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase().split('-')[0];
  const found = SUPPORTED_LANGUAGES.find(lang => lang.code === browserLang);
  return found || SUPPORTED_LANGUAGES[0]; // Default to English
};
