export interface Language {
  code: string;
  name: string;
  flag: string;
  greeting: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', greeting: 'Welcome' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', greeting: 'أهلاً وسهلاً' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', greeting: 'Добро пожаловать' },
  { code: 'zh', name: '中文', flag: '🇨🇳', greeting: '欢迎' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', greeting: 'स्वागत है' },
  { code: 'es', name: 'Español', flag: '🇪🇸', greeting: 'Bienvenido' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', greeting: 'Bienvenue' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', greeting: 'Willkommen' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', greeting: 'ようこそ' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷', greeting: 'Hoş geldiniz' },
  { code: 'pt', name: 'Português', flag: '🇵🇹', greeting: 'Bem-vindo' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦', greeting: 'Ласкаво просимо' },
];

// Keep the old export for backward compatibility
export const languages: Language[] = SUPPORTED_LANGUAGES;

export const detectLanguage = (): Language => {
  const browserLang = navigator.language.split('-')[0];
  return SUPPORTED_LANGUAGES.find(lang => lang.code === browserLang) || SUPPORTED_LANGUAGES[0];
};

const translations: Record<string, Record<string, string>> = {
  en: {
    mining: 'Mining',
    tasks: 'Tasks',
    wallet: 'Wallet',
    friends: 'Friends',
    premium: 'Premium',
    spaceBalance: '$SPACE Balance',
    miningSpeed: 'Mining Speed',
    timeRemaining: 'Time Remaining',
    startMining: 'Start Mining',
    stopMining: 'Stop Mining',
    upgradeMiningSpeed: 'Upgrade Mining Speed',
    fasterMining: 'faster mining',
    autoMining: 'Auto Mining',
    autoMiningActive: 'Auto Mining Active',
    enableAutoMining: 'Enable Auto Mining',
    autoMiningDesc: 'Enable automatic mining that restarts every 8 hours without manual intervention',
    changeBackground: 'Change Background',
    currentBackground: 'Current',
    free: 'Free',
    active: 'Active',
    oneTimePurchase: 'One-time purchase',
    purchaseAutoMining: 'Purchase Auto Mining',
    subscriptions: 'Subscriptions',
    unlockPremiumFeatures: 'Unlock premium features and boost your mining',
    freePlan: 'Free',
    premiumPlan: 'Premium',
    vipPlan: 'VIP',
    forever: 'Forever',
    perMonth: 'per month',
    popular: 'Popular',
    current: 'Current',
    currentPlan: 'Current Plan',
    selectPlan: 'Select Plan',
    subscribe: 'Subscribe',
    featureComparison: 'Feature Comparison',
    customization: 'Customization',
    basicMining: 'Basic mining',
    standardSpeed: 'Standard speed (1x)',
    basicTasks: 'Basic tasks',
    communitySupport: 'Community support',
    fastSpeed: 'Fast speed (5x)',
    premiumTasks: 'Premium tasks',
    backgroundChange: 'Background customization',
    prioritySupport: 'Priority support',
    earlyAccess: 'Early access to features',
    ultraFastMining: 'Ultra-fast mining (10x)',
    unlimitedAutoMining: 'Unlimited auto mining',
    exclusiveTasks: 'Exclusive VIP tasks',
    customBackgrounds: 'Custom backgrounds',
    vipSupport: '24/7 VIP support',
    specialRewards: 'Special rewards & bonuses',
    exclusiveFeatures: 'Exclusive features',
    exclusiveBackgrounds: 'Exclusive Backgrounds',
    exclusiveBackgroundsDesc: 'Premium-only visual themes',
    vipBadge: 'VIP Badge',
    vipBadgeDesc: 'Show your premium status',
    premiumBenefits: 'Premium Benefits',
    bonusPoints: 'Bonus Points',
    bonusPointsDesc: '+25% extra points on all tasks',
    subscribeNow: 'Subscribe Now',
    processing: 'Processing...',
    walletRequired: 'Wallet Required',
    connectWalletFirst: 'Please connect your TON wallet first',
    subscriptionSuccess: 'Subscription Successful',
    premiumActivated: 'Premium plan activated successfully!',
    paymentFailed: 'Payment Failed',
    subscriptionError: 'Failed to process subscription payment',
    completeTasksEarn: 'Complete tasks to earn $SPACE coins',
    tasksCompleted: 'Tasks Completed',
    noTasksAvailable: 'No Tasks Available',
    noTasksDesc: 'New tasks will be added soon. Stay tuned!',
    inviteFriendsEarn: 'Invite friends and earn $SPACE coins together',
    totalReferrals: 'Total Referrals',
    totalEarned: 'Total Earned',
    airdropBonus: 'Airdrop Bonus',
    getReferralLink: 'Get Your Referral Link',
    goToBot: 'Go to',
    onTelegram: 'on Telegram',
    sendCommand: 'Send the command',
    receiveLink: 'You will receive your personal referral link',
    openBot: 'Open @Spacelbot',
    // Wallet page translations
    smartWallet: 'Smart Wallet',
    walletDescription: 'Secure & Fast TON Blockchain Wallet',
    connectWallet: 'Connect Wallet',
    connectWalletToAccess: 'Connect your wallet to access features',
    connecting: 'Connecting...',
    walletConnected: 'Wallet Connected',
    disconnectWallet: 'Disconnect',
    mainCurrency: 'Main Currency',
    walletAddress: 'Wallet Address',
    latestTransactions: 'Latest Transactions',
    loadingTransactions: 'Loading transactions...',
    noTransactions: 'No Transactions',
    startSendingReceiving: 'Start sending and receiving coins',
    copied: 'Copied!',
    walletAddressCopied: 'Wallet address copied to clipboard',
    openConnectionWindow: 'Opening Connection Window',
    pleaseSelectWallet: 'Please select your preferred wallet',
    connectionError: 'Connection Error',
    failedToOpenWallet: 'Failed to open wallet connection',
    disconnected: 'Disconnected',
    tonWalletDisconnected: 'TON wallet has been disconnected',
    loadingDataError: 'Loading Data Error',
    failedToLoadWallet: 'Failed to load wallet data'
  },
  ar: {
    mining: 'التعدين',
    tasks: 'المهام',
    wallet: 'المحفظة',
    friends: 'الأصدقاء',
    premium: 'مميز',
    spaceBalance: 'رصيد $SPACE',
    miningSpeed: 'سرعة التعدين',
    timeRemaining: 'الوقت المتبقي',
    startMining: 'ابدأ التعدين',
    stopMining: 'أوقف التعدين',
    upgradeMiningSpeed: 'ترقية سرعة التعدين',
    fasterMining: 'تعدين أسرع',
    autoMining: 'التعدين التلقائي',
    autoMiningActive: 'التعدين التلقائي نشط',
    enableAutoMining: 'تفعيل التعدين التلقائي',
    autoMiningDesc: 'تفعيل التعدين التلقائي الذي يعيد التشغيل كل 8 ساعات دون تدخل يدوي',
    changeBackground: 'تغيير الخلفية',
    currentBackground: 'الحالية',
    free: 'مجاني',
    active: 'نشط',
    oneTimePurchase: 'شراء لمرة واحدة',
    purchaseAutoMining: 'شراء التعدين التلقائي',
    subscriptions: 'الاشتراكات',
    unlockPremiumFeatures: 'افتح المميزات المتقدمة وعزز تعدينك',
    freePlan: 'مجاني',
    premiumPlan: 'مميز',
    vipPlan: 'في آي بي',
    forever: 'للأبد',
    perMonth: 'في الشهر',
    popular: 'شائع',
    current: 'الحالي',
    currentPlan: 'الخطة الحالية',
    selectPlan: 'اختر الخطة',
    subscribe: 'اشترك',
    featureComparison: 'مقارنة المميزات',
    customization: 'التخصيص',
    basicMining: 'تعدين أساسي',
    standardSpeed: 'سرعة عادية (1x)',
    basicTasks: 'مهام أساسية',
    communitySupport: 'دعم المجتمع',
    fastSpeed: 'سرعة سريعة (5x)',
    premiumTasks: 'مهام مميزة',
    backgroundChange: 'تخصيص الخلفية',
    prioritySupport: 'دعم أولوي',
    earlyAccess: 'وصول مبكر للمميزات',
    ultraFastMining: 'تعدين فائق السرعة (10x)',
    unlimitedAutoMining: 'تعدين تلقائي غير محدود',
    exclusiveTasks: 'مهام VIP حصرية',
    customBackgrounds: 'خلفيات مخصصة',
    vipSupport: 'دعم VIP على مدار الساعة',
    specialRewards: 'مكافآت ومكافآت خاصة',
    exclusiveFeatures: 'مميزات حصرية',
    exclusiveBackgrounds: 'خلفيات حصرية',
    exclusiveBackgroundsDesc: 'مواضيع بصرية حصرية للمشتركين',
    vipBadge: 'شارة VIP',
    vipBadgeDesc: 'اعرض حالة الاشتراك المميز',
    premiumBenefits: 'مميزات الاشتراك المميز',
    bonusPoints: 'نقاط مكافأة',
    bonusPointsDesc: '+25% نقاط إضافية على جميع المهام',
    subscribeNow: 'اشترك الآن',
    processing: 'جاري المعالجة...',
    walletRequired: 'مطلوب محفظة',
    connectWalletFirst: 'يرجى ربط محفظة TON أولاً',
    subscriptionSuccess: 'تم الاشتراك بنجاح',
    premiumActivated: 'تم تفعيل الخطة المميزة بنجاح!',
    paymentFailed: 'فشل في الدفع',
    subscriptionError: 'فشل في معالجة دفعة الاشتراك',
    completeTasksEarn: 'أكمل المهام لكسب عملات $SPACE',
    tasksCompleted: 'المهام المكتملة',
    noTasksAvailable: 'لا توجد مهام متاحة',
    noTasksDesc: 'سيتم إضافة مهام جديدة قريباً. ترقبوا!',
    inviteFriendsEarn: 'ادع الأصدقاء واكسبوا عملات $SPACE معاً',
    totalReferrals: 'إجمالي الإحالات',
    totalEarned: 'إجمالي المكتسب',
    airdropBonus: 'مكافأة الإسقاط الجوي',
    getReferralLink: 'احصل على رابط الإحالة',
    goToBot: 'اذهب إلى',
    onTelegram: 'على تليجرام',
    sendCommand: 'أرسل الأمر',
    receiveLink: 'ستحصل على رابط الإحالة الشخصي',
    openBot: 'افتح @Spacelbot',
    // Wallet page translations
    smartWallet: 'المحفظة الذكية',
    walletDescription: 'محفظة TON آمنة وسريعة',
    connectWallet: 'ربط المحفظة',
    connectWalletToAccess: 'اربط محفظتك للوصول إلى المميزات',
    connecting: 'جاري الاتصال...',
    walletConnected: 'تم ربط المحفظة',
    disconnectWallet: 'قطع الاتصال',
    mainCurrency: 'العملة الرئيسية',
    walletAddress: 'عنوان المحفظة',
    latestTransactions: 'آخر المعاملات',
    loadingTransactions: 'جاري تحميل المعاملات...',
    noTransactions: 'لا توجد معاملات',
    startSendingReceiving: 'ابدأ بإرسال واستقبال العملات',
    copied: 'تم النسخ!',
    walletAddressCopied: 'تم نسخ عنوان المحفظة',
    openConnectionWindow: 'فتح نافذة الاتصال',
    pleaseSelectWallet: 'يرجى اختيار محفظتك المفضلة',
    connectionError: 'خطأ في الاتصال',
    failedToOpenWallet: 'فشل في فتح اتصال المحفظة',
    disconnected: 'تم قطع الاتصال',
    tonWalletDisconnected: 'تم قطع اتصال محفظة TON',
    loadingDataError: 'خطأ في تحميل البيانات',
    failedToLoadWallet: 'فشل في تحميل بيانات المحفظة'
  },
  ru: {
    mining: 'Майнинг',
    tasks: 'Задания',
    wallet: 'Кошелек',
    friends: 'Друзья',
    premium: 'Премиум',
    spaceBalance: 'Баланс $SPACE',
    miningSpeed: 'Скорость майнинга',
    timeRemaining: 'Оставшееся время',
    startMining: 'Начать майнинг',
    stopMining: 'Остановить майнинг',
    upgradeMiningSpeed: 'Улучшить скорость майнинга',
    fasterMining: 'более быстрый майнинг',
    autoMining: 'Автомайнинг',
    autoMiningActive: 'Автомайнинг активен',
    enableAutoMining: 'Включить автомайнинг',
    autoMiningDesc: 'Включите автоматический майнинг, который перезапускается каждые 8 часов без ручного вмешательства',
    changeBackground: 'Изменить фон',
    currentBackground: 'Текущий',
    free: 'Бесплатно',
    active: 'Активен',
    oneTimePurchase: 'Разовая покупка',
    purchaseAutoMining: 'Купить автомайнинг',
    subscriptions: 'Подписки',
    unlockPremiumFeatures: 'Разблокируйте премиум-функции и увеличьте свой майнинг',
    freePlan: 'Бесплатный',
    premiumPlan: 'Премиум',
    vipPlan: 'VIP',
    forever: 'Навсегда',
    perMonth: 'в месяц',
    popular: 'Популярный',
    current: 'Текущий',
    currentPlan: 'Текущий план',
    selectPlan: 'Выбрать план',
    subscribe: 'Подписаться',
    featureComparison: 'Сравнение функций',
    customization: 'Настройка',
    basicMining: 'Базовый майнинг',
    standardSpeed: 'Стандартная скорость (1x)',
    basicTasks: 'Базовые задачи',
    communitySupport: 'Поддержка сообщества',
    fastSpeed: 'Быстрая скорость (5x)',
    premiumTasks: 'Премиум задачи',
    backgroundChange: 'Настройка фона',
    prioritySupport: 'Приоритетная поддержка',
    earlyAccess: 'Ранний доступ к функциям',
    ultraFastMining: 'Ультра-быстрый майнинг (10x)',
    unlimitedAutoMining: 'Неограниченный автомайнинг',
    exclusiveTasks: 'Эксклюзивные VIP задачи',
    customBackgrounds: 'Пользовательские фоны',
    vipSupport: 'Круглосуточная VIP поддержка',
    specialRewards: 'Специальные награды и бонусы',
    exclusiveFeatures: 'Эксклюзивные функции',
    exclusiveBackgrounds: 'Эксклюзивные фоны',
    exclusiveBackgroundsDesc: 'Визуальные темы только для премиум',
    vipBadge: 'VIP значок',
    vipBadgeDesc: 'Покажите свой премиум статус',
    premiumBenefits: 'Премиум преимущества',
    bonusPoints: 'Бонусные очки',
    bonusPointsDesc: '+25% дополнительных очков за все задачи',
    subscribeNow: 'Подписаться сейчас',
    processing: 'Обработка...',
    walletRequired: 'Требуется кошелек',
    connectWalletFirst: 'Пожалуйста, подключите кошелек TON сначала',
    subscriptionSuccess: 'Подписка успешна',
    premiumActivated: 'Премиум план активирован успешно!',
    paymentFailed: 'Платеж не удался',
    subscriptionError: 'Не удалось обработать платеж подписки',
    completeTasksEarn: 'Выполняйте задачи, чтобы заработать монеты $SPACE',
    tasksCompleted: 'Задачи выполнены',
    noTasksAvailable: 'Нет доступных задач',
    noTasksDesc: 'Новые задачи будут добавлены в ближайшее время. Следите за обновлениями!',
    inviteFriendsEarn: 'Приглашайте друзей и зарабатывайте монеты $SPACE вместе',
    totalReferrals: 'Общие рефералы',
    totalEarned: 'Всего заработано',
    airdropBonus: 'Бонус аирдропа',
    getReferralLink: 'Получить реферальную ссылку',
    goToBot: 'Перейти к',
    onTelegram: 'в Telegram',
    sendCommand: 'Отправить команду',
    receiveLink: 'Вы получите свою персональную реферальную ссылку',
    openBot: 'Открыть @Spacelbot',
    smartWallet: 'Умный кошелек',
    walletDescription: 'Безопасный и быстрый кошелек TON',
    connectWallet: 'Подключить кошелек',
    connectWalletToAccess: 'Подключите кошелек для доступа к функциям',
    connecting: 'Подключение...',
    walletConnected: 'Кошелек подключен',
    disconnectWallet: 'Отключить',
    mainCurrency: 'Основная валюта',
    walletAddress: 'Адрес кошелька',
    latestTransactions: 'Последние транзакции',
    loadingTransactions: 'Загрузка транзакций...',
    noTransactions: 'Нет транзакций',
    startSendingReceiving: 'Начните отправлять и получать монеты',
    copied: 'Скопировано!',
    walletAddressCopied: 'Адрес кошелька скопирован',
    openConnectionWindow: 'Открытие окна подключения',
    pleaseSelectWallet: 'Пожалуйста, выберите предпочитаемый кошелек',
    connectionError: 'Ошибка подключения',
    failedToOpenWallet: 'Не удалось открыть подключение кошелька',
    disconnected: 'Отключено',
    tonWalletDisconnected: 'Кошелек TON отключен',
    loadingDataError: 'Ошибка загрузки данных',
    failedToLoadWallet: 'Не удалось загрузить данные кошелька'
  },
  zh: {
    mining: '挖矿',
    tasks: '任务',
    wallet: '钱包',
    friends: '朋友',
    premium: '高级',
    spaceBalance: '$SPACE 余额',
    miningSpeed: '挖矿速度',
    timeRemaining: '剩余时间',
    startMining: '开始挖矿',
    stopMining: '停止挖矿',
    upgradeMiningSpeed: '升级挖矿速度',
    fasterMining: '更快的挖矿速度',
    autoMining: '自动挖矿',
    autoMiningActive: '自动挖矿已激活',
    enableAutoMining: '启用自动挖矿',
    autoMiningDesc: '启用自动挖矿，无需手动干预即可每 8 小时重新启动',
    changeBackground: '更换背景',
    currentBackground: '当前背景',
    free: '免费',
    active: '已激活',
    oneTimePurchase: '一次性购买',
    purchaseAutoMining: '购买自动挖矿',
    subscriptions: '订阅',
    unlockPremiumFeatures: '解锁高级功能并提升您的挖矿效率',
    freePlan: '免费计划',
    premiumPlan: '高级计划',
    vipPlan: 'VIP 计划',
    forever: '永久',
    perMonth: '每月',
    popular: '受欢迎',
    current: '当前',
    currentPlan: '当前计划',
    selectPlan: '选择计划',
    subscribe: '订阅',
    featureComparison: '功能比较',
    customization: '自定义',
    basicMining: '基础挖矿',
    standardSpeed: '标准速度 (1x)',
    basicTasks: '基础任务',
    communitySupport: '社区支持',
    fastSpeed: '快速速度 (5x)',
    premiumTasks: '高级任务',
    backgroundChange: '背景自定义',
    prioritySupport: '优先支持',
    earlyAccess: '提前体验功能',
    ultraFastMining: '超快速挖矿 (10x)',
    unlimitedAutoMining: '无限自动挖矿',
    exclusiveTasks: '独家 VIP 任务',
    customBackgrounds: '自定义背景',
    vipSupport: '24/7 VIP 支持',
    specialRewards: '特殊奖励和红利',
    exclusiveFeatures: '独家功能',
    exclusiveBackgrounds: '专享背景',
    exclusiveBackgroundsDesc: '仅限高级会员的视觉主题',
    vipBadge: 'VIP 徽章',
    vipBadgeDesc: '展示您的高级会员身份',
    premiumBenefits: '高级会员福利',
    bonusPoints: '奖励积分',
    bonusPointsDesc: '所有任务额外获得 +25% 积分',
    subscribeNow: '立即订阅',
    processing: '处理中...',
    walletRequired: '需要钱包',
    connectWalletFirst: '请先连接您的 TON 钱包',
    subscriptionSuccess: '订阅成功',
    premiumActivated: '高级计划已成功激活！',
    paymentFailed: '支付失败',
    subscriptionError: '处理订阅付款失败',
    completeTasksEarn: '完成任务以赚取 $SPACE 币',
    tasksCompleted: '已完成任务',
    noTasksAvailable: '暂无可用任务',
    noTasksDesc: '新任务即将添加。敬请期待！',
    inviteFriendsEarn: '邀请朋友一起赚取 $SPACE 币',
    totalReferrals: '总推荐数',
    totalEarned: '总收益',
    airdropBonus: '空投奖励',
    getReferralLink: '获取推荐链接',
    goToBot: '前往',
    onTelegram: '在 Telegram 上',
    sendCommand: '发送命令',
    receiveLink: '您将收到您的个人推荐链接',
    openBot: '打开 @Spacelbot',
    smartWallet: '智能钱包',
    walletDescription: '安全快速的 TON 区块链钱包',
    connectWallet: '连接钱包',
    connectWalletToAccess: '连接您的钱包以访问功能',
    connecting: '连接中...',
    walletConnected: '钱包已连接',
    disconnectWallet: '断开连接',
    mainCurrency: '主要货币',
    walletAddress: '钱包地址',
    latestTransactions: '最新交易',
    loadingTransactions: '加载交易中...',
    noTransactions: '无交易记录',
    startSendingReceiving: '开始发送和接收货币',
    copied: '已复制！',
    walletAddressCopied: '钱包地址已复制',
    openConnectionWindow: '打开连接窗口',
    pleaseSelectWallet: '请选择您喜欢的钱包',
    connectionError: '连接错误',
    failedToOpenWallet: '无法打开钱包连接',
    disconnected: '已断开连接',
    tonWalletDisconnected: 'TON 钱包已断开连接',
    loadingDataError: '加载数据错误',
    failedToLoadWallet: '无法加载钱包数据'
  },
  hi: {
    mining: 'खनन',
    tasks: 'कार्य',
    wallet: 'वॉलेट',
    friends: 'दोस्त',
    premium: 'प्रीमियम',
    spaceBalance: '$SPACE बैलेंस',
    miningSpeed: 'खनन गति',
    timeRemaining: 'शेष समय',
    startMining: 'खनन शुरू करें',
    stopMining: 'खनन रोकें',
    upgradeMiningSpeed: 'खनन गति बढ़ाएँ',
    fasterMining: 'तेज़ खनन',
    autoMining: 'स्वचालित खनन',
    autoMiningActive: 'स्वचालित खनन सक्रिय',
    enableAutoMining: 'स्वचालित खनन सक्षम करें',
    autoMiningDesc: 'स्वचालित खनन सक्षम करें जो बिना किसी हस्त हस्तक्षेप के हर 8 घंटे में पुनरारंभ होता है',
    changeBackground: 'पृष्ठभूमि बदलें',
    currentBackground: 'वर्तमान',
    free: 'मुफ्त',
    active: 'सक्रिय',
    oneTimePurchase: 'एकबारगी खरीद',
    purchaseAutoMining: 'स्वचालित खनन खरीदें',
    subscriptions: 'सदस्यताएँ',
    unlockPremiumFeatures: 'प्रीमियम सुविधाएँ अनलॉक करें और अपने खनन को बढ़ावा दें',
    freePlan: 'मुफ्त योजना',
    premiumPlan: 'प्रीमियम योजना',
    vipPlan: 'वीआईपी योजना',
    forever: 'हमेशा के लिए',
    perMonth: 'प्रति माह',
    popular: 'लोकप्रिय',
    current: 'वर्तमान',
    currentPlan: 'वर्तमान योजना',
    selectPlan: 'योजना का चयन करें',
    subscribe: 'सदस्यता लें',
    featureComparison: 'सुविधा तुलना',
    customization: 'अनुकूलन',
    basicMining: 'बुनियादी खनन',
    standardSpeed: 'मानक गति (1x)',
    basicTasks: 'बुनियादी कार्य',
    communitySupport: 'सामुदायिक समर्थन',
    fastSpeed: 'तेज़ गति (5x)',
    premiumTasks: 'प्रीमियम कार्य',
    backgroundChange: 'पृष्ठभूमि अनुकूलन',
    prioritySupport: 'प्राथमिकता समर्थन',
    earlyAccess: 'सुविधाओं तक शीघ्र पहुंच',
    ultraFastMining: 'अल्ट्रा-फास्ट खनन (10x)',
    unlimitedAutoMining: 'असीमित स्वचालित खनन',
    exclusiveTasks: 'विशेष वीआईपी कार्य',
    customBackgrounds: 'कस्टम पृष्ठभूमि',
    vipSupport: '24/7 वीआईपी समर्थन',
    specialRewards: 'विशेष पुरस्कार और बोनस',
    exclusiveFeatures: 'विशेष सुविधाएँ',
    exclusiveBackgrounds: 'विशेष पृष्ठभूमि',
    exclusiveBackgroundsDesc: 'केवल प्रीमियम के लिए दृश्य थीम',
    vipBadge: 'वीआईपी बैज',
    vipBadgeDesc: 'अपनी प्रीमियम स्थिति दिखाएं',
    premiumBenefits: 'प्रीमियम लाभ',
    bonusPoints: 'बोनस अंक',
    bonusPointsDesc: 'सभी कार्यों पर +25% अतिरिक्त अंक',
    subscribeNow: 'अभी सदस्यता लें',
    processing: 'प्रसंस्करण...',
    walletRequired: 'वॉलेट आवश्यक',
    connectWalletFirst: 'कृपया पहले अपना TON वॉलेट कनेक्ट करें',
    subscriptionSuccess: 'सदस्यता सफल',
    premiumActivated: 'प्रीमियम योजना सफलतापूर्वक सक्रिय!',
    paymentFailed: 'भुगतान विफल',
    subscriptionError: 'सदस्यता भुगतान संसाधित करने में विफल',
    completeTasksEarn: '$SPACE सिक्के कमाने के लिए कार्य पूरे करें',
    tasksCompleted: 'कार्य पूर्ण',
    noTasksAvailable: 'कोई कार्य उपलब्ध नहीं',
    noTasksDesc: 'नए कार्य जल्द ही जोड़े जाएंगे। बने रहें!',
    inviteFriendsEarn: 'दोस्तों को आमंत्रित करें और एक साथ $SPACE सिक्के कमाएं',
    totalReferrals: 'कुल रेफरल',
    totalEarned: 'कुल कमाई',
    airdropBonus: 'एयरड्रॉप बोनस',
    getReferralLink: 'रेफरल लिंक प्राप्त करें',
    goToBot: 'जाएं',
    onTelegram: 'टेलीग्राम पर',
    sendCommand: 'कमांड भेजें',
    receiveLink: 'आपको अपना व्यक्तिगत रेफरल लिंक मिलेगा',
    openBot: '@Spacelbot खोलें',
    smartWallet: 'स्मार्ट वॉलेट',
    walletDescription: 'सुरक्षित और तेज़ TON ब्लॉकचेन वॉलेट',
    connectWallet: 'वॉलेट कनेक्ट करें',
    connectWalletToAccess: 'सुविधाओं तक पहुंचने के लिए अपना वॉलेट कनेक्ट करें',
    connecting: 'कनेक्ट हो रहा है...',
    walletConnected: 'वॉलेट कनेक्टेड',
    disconnectWallet: 'डिस्कनेक्ट करें',
    mainCurrency: 'मुख्य मुद्रा',
    walletAddress: 'वॉलेट पता',
    latestTransactions: 'नवीनतम लेनदेन',
    loadingTransactions: 'लेनदेन लोड हो रहे हैं...',
    noTransactions: 'कोई लेनदेन नहीं',
    startSendingReceiving: 'सिक्के भेजना और प्राप्त करना शुरू करें',
    copied: 'कॉपी किया गया!',
    walletAddressCopied: 'वॉलेट पता कॉपी किया गया',
    openConnectionWindow: 'कनेक्शन विंडो खोली जा रही है',
    pleaseSelectWallet: 'कृपया अपना पसंदीदा वॉलेट चुनें',
    connectionError: 'कनेक्शन त्रुटि',
    failedToOpenWallet: 'वॉलेट कनेक्शन खोलने में विफल',
    disconnected: 'डिस्कनेक्ट किया गया',
    tonWalletDisconnected: 'TON वॉलेट डिस्कनेक्ट किया गया है',
    loadingDataError: 'डेटा लोड करने में त्रुटि',
    failedToLoadWallet: 'वॉलेट डेटा लोड करने में विफल'
  },
  es: {
    mining: 'Minería',
    tasks: 'Tareas',
    wallet: 'Billetera',
    friends: 'Amigos',
    premium: 'Premium',
    spaceBalance: 'Saldo $SPACE',
    miningSpeed: 'Velocidad de minería',
    timeRemaining: 'Tiempo restante',
    startMining: 'Comenzar a minar',
    stopMining: 'Detener la minería',
    upgradeMiningSpeed: 'Mejorar la velocidad de minería',
    fasterMining: 'minería más rápida',
    autoMining: 'Minería automática',
    autoMiningActive: 'Minería automática activa',
    enableAutoMining: 'Habilitar la minería automática',
    autoMiningDesc: 'Habilita la minería automática que se reinicia cada 8 horas sin intervención manual',
    changeBackground: 'Cambiar el fondo',
    currentBackground: 'Actual',
    free: 'Gratis',
    active: 'Activo',
    oneTimePurchase: 'Compra única',
    purchaseAutoMining: 'Comprar minería automática',
    subscriptions: 'Suscripciones',
    unlockPremiumFeatures: 'Desbloquea funciones premium y aumenta tu minería',
    freePlan: 'Gratis',
    premiumPlan: 'Premium',
    vipPlan: 'VIP',
    forever: 'Para siempre',
    perMonth: 'por mes',
    popular: 'Popular',
    current: 'Actual',
    currentPlan: 'Plan actual',
    selectPlan: 'Seleccionar plan',
    subscribe: 'Suscribirse',
    featureComparison: 'Comparación de características',
    customization: 'Personalización',
    basicMining: 'Minería básica',
    standardSpeed: 'Velocidad estándar (1x)',
    basicTasks: 'Tareas básicas',
    communitySupport: 'Soporte comunitario',
    fastSpeed: 'Velocidad rápida (5x)',
    premiumTasks: 'Tareas premium',
    backgroundChange: 'Personalización de fondo',
    prioritySupport: 'Soporte prioritario',
    earlyAccess: 'Acceso anticipado a funciones',
    ultraFastMining: 'Minería ultrarrápida (10x)',
    unlimitedAutoMining: 'Minería automática ilimitada',
    exclusiveTasks: 'Tareas VIP exclusivas',
    customBackgrounds: 'Fondos personalizados',
    vipSupport: 'Soporte VIP 24/7',
    specialRewards: 'Recompensas y bonificaciones especiales',
    exclusiveFeatures: 'Características exclusivas',
    exclusiveBackgrounds: 'Fondos exclusivos',
    exclusiveBackgroundsDesc: 'Temas visuales solo para premium',
    vipBadge: 'Insignia VIP',
    vipBadgeDesc: 'Muestra tu estado premium',
    premiumBenefits: 'Beneficios premium',
    bonusPoints: 'Puntos de bonificación',
    bonusPointsDesc: '+25% puntos extra en todas las tareas',
    subscribeNow: 'Suscribirse ahora',
    processing: 'Procesando...',
    walletRequired: 'Billetera requerida',
    connectWalletFirst: 'Por favor conecta tu billetera TON primero',
    subscriptionSuccess: 'Suscripción exitosa',
    premiumActivated: '¡Plan premium activado exitosamente!',
    paymentFailed: 'Pago fallido',
    subscriptionError: 'Error al procesar el pago de suscripción',
    completeTasksEarn: 'Completa tareas para ganar monedas $SPACE',
    tasksCompleted: 'Tareas completadas',
    noTasksAvailable: 'No hay tareas disponibles',
    noTasksDesc: 'Se agregarán nuevas tareas pronto. ¡Mantente atento!',
    inviteFriendsEarn: 'Invita amigos y ganen monedas $SPACE juntos',
    totalReferrals: 'Referidos totales',
    totalEarned: 'Total ganado',
    airdropBonus: 'Bonificación de airdrop',
    getReferralLink: 'Obtener enlace de referido',
    goToBot: 'Ir a',
    onTelegram: 'en Telegram',
    sendCommand: 'Enviar el comando',
    receiveLink: 'Recibirás tu enlace de referido personal',
    openBot: 'Abrir @Spacelbot',
    smartWallet: 'Billetera Inteligente',
    walletDescription: 'Billetera TON segura y rápida',
    connectWallet: 'Conectar Billetera',
    connectWalletToAccess: 'Conecta tu billetera para acceder a las funciones',
    connecting: 'Conectando...',
    walletConnected: 'Billetera Conectada',
    disconnectWallet: 'Desconectar',
    mainCurrency: 'Moneda Principal',
    walletAddress: 'Dirección de Billetera',
    latestTransactions: 'Transacciones Recientes',
    loadingTransactions: 'Cargando transacciones...',
    noTransactions: 'Sin Transacciones',
    startSendingReceiving: 'Comienza a enviar y recibir monedas',
    copied: '¡Copiado!',
    walletAddressCopied: 'Dirección de billetera copiada',
    openConnectionWindow: 'Abriendo ventana de conexión',
    pleaseSelectWallet: 'Por favor selecciona tu billetera preferida',
    connectionError: 'Error de conexión',
    failedToOpenWallet: 'Error al abrir la conexión de billetera',
    disconnected: 'Desconectado',
    tonWalletDisconnected: 'Billetera TON desconectada',
    loadingDataError: 'Error al cargar datos',
    failedToLoadWallet: 'Error al cargar datos de billetera'
  },
  fr: {
    mining: 'Minage',
    tasks: 'Tâches',
    wallet: 'Portefeuille',
    friends: 'Amis',
    premium: 'Premium',
    spaceBalance: 'Solde $SPACE',
    miningSpeed: 'Vitesse de minage',
    timeRemaining: 'Temps restant',
    startMining: 'Commencer à miner',
    stopMining: 'Arrêter le minage',
    upgradeMiningSpeed: 'Améliorer la vitesse de minage',
    fasterMining: 'minage plus rapide',
    autoMining: 'Minage automatique',
    autoMiningActive: 'Minage automatique actif',
    enableAutoMining: 'Activer le minage automatique',
    autoMiningDesc: 'Activez le minage automatique qui redémarre toutes les 8 heures sans intervention manuelle',
    changeBackground: 'Changer le fond',
    currentBackground: 'Actuel',
    free: 'Gratuit',
    active: 'Actif',
    oneTimePurchase: 'Achat unique',
    purchaseAutoMining: 'Acheter le minage automatique',
    subscriptions: 'Abonnements',
    unlockPremiumFeatures: 'Débloquez des fonctionnalités premium et boostez votre minage',
    freePlan: 'Gratuit',
    premiumPlan: 'Premium',
    vipPlan: 'VIP',
    forever: 'Pour toujours',
    perMonth: 'par mois',
    popular: 'Populaire',
    current: 'Actuel',
    currentPlan: 'Plan actuel',
    selectPlan: 'Sélectionner le plan',
    subscribe: 'S\'abonner',
    featureComparison: 'Comparaison des fonctionnalités',
    customization: 'Personnalisation',
    basicMining: 'Minage de base',
    standardSpeed: 'Vitesse standard (1x)',
    basicTasks: 'Tâches de base',
    communitySupport: 'Support communautaire',
    fastSpeed: 'Vitesse rapide (5x)',
    premiumTasks: 'Tâches premium',
    backgroundChange: 'Personnalisation de fond',
    prioritySupport: 'Support prioritaire',
    earlyAccess: 'Accès anticipé aux fonctionnalités',
    ultraFastMining: 'Minage ultra-rapide (10x)',
    unlimitedAutoMining: 'Minage automatique illimité',
    exclusiveTasks: 'Tâches VIP exclusives',
    customBackgrounds: 'Fonds personnalisés',
    vipSupport: 'Support VIP 24/7',
    specialRewards: 'Récompenses et bonus spéciaux',
    exclusiveFeatures: 'Fonctionnalités exclusives',
    exclusiveBackgrounds: 'Arrière-plans exclusifs',
    exclusiveBackgroundsDesc: 'Thèmes visuels réservés aux premium',
    vipBadge: 'Badge VIP',
    vipBadgeDesc: 'Affichez votre statut premium',
    premiumBenefits: 'Avantages premium',
    bonusPoints: 'Points bonus',
    bonusPointsDesc: '+25% de points supplémentaires sur toutes les tâches',
    subscribeNow: 'S\'abonner maintenant',
    processing: 'Traitement...',
    walletRequired: 'Portefeuille requis',
    connectWalletFirst: 'Veuillez d\'abord connecter votre portefeuille TON',
    subscriptionSuccess: 'Abonnement réussi',
    premiumActivated: 'Plan premium activé avec succès !',
    paymentFailed: 'Paiement échoué',
    subscriptionError: 'Échec du traitement du paiement d\'abonnement',
    completeTasksEarn: 'Complétez des tâches pour gagner des pièces $SPACE',
    tasksCompleted: 'Tâches terminées',
    noTasksAvailable: 'Aucune tâche disponible',
    noTasksDesc: 'De nouvelles tâches seront ajoutées bientôt. Restez à l\'écoute !',
    inviteFriendsEarn: 'Invitez des amis et gagnez des pièces $SPACE ensemble',
    totalReferrals: 'Total des parrainages',
    totalEarned: 'Total gagné',
    airdropBonus: 'Bonus airdrop',
    getReferralLink: 'Obtenir le lien de parrainage',
    goToBot: 'Aller à',
    onTelegram: 'sur Telegram',
    sendCommand: 'Envoyer la commande',
    receiveLink: 'Vous recevrez votre lien de parrainage personnel',
    openBot: 'Ouvrir @Spacelbot',
    smartWallet: 'Portefeuille Intelligent',
    walletDescription: 'Portefeuille TON sécurisé et rapide',
    connectWallet: 'Connecter Portefeuille',
    connectWalletToAccess: 'Connectez votre portefeuille pour accéder aux fonctionnalités',
    connecting: 'Connexion...',
    walletConnected: 'Portefeuille Connecté',
    disconnectWallet: 'Déconnecter',
    mainCurrency: 'Devise Principale',
    walletAddress: 'Adresse du Portefeuille',
    latestTransactions: 'Dernières Transactions',
    loadingTransactions: 'Chargement des transactions...',
    noTransactions: 'Aucune Transaction',
    startSendingReceiving: 'Commencez à envoyer et recevoir des pièces',
    copied: 'Copié !',
    walletAddressCopied: 'Adresse du portefeuille copiée',
    openConnectionWindow: 'Ouverture de la fenêtre de connexion',
    pleaseSelectWallet: 'Veuillez sélectionner votre portefeuille préféré',
    connectionError: 'Erreur de connexion',
    failedToOpenWallet: 'Échec de l\'ouverture de la connexion du portefeuille',
    disconnected: 'Déconnecté',
    tonWalletDisconnected: 'Portefeuille TON déconnecté',
    loadingDataError: 'Erreur de chargement des données',
    failedToLoadWallet: 'Échec du chargement des données du portefeuille'
  },
  de: {
    mining: 'Mining',
    tasks: 'Aufgaben',
    wallet: 'Wallet',
    friends: 'Freunde',
    premium: 'Premium',
    spaceBalance: '$SPACE Guthaben',
    miningSpeed: 'Mining-Geschwindigkeit',
    timeRemaining: 'Verbleibende Zeit',
    startMining: 'Starte Mining',
    stopMining: 'Stoppe Mining',
    upgradeMiningSpeed: 'Verbessere Mining-Geschwindigkeit',
    fasterMining: 'schnelleres Mining',
    autoMining: 'Auto-Mining',
    autoMiningActive: 'Auto-Mining aktiv',
    enableAutoMining: 'Aktiviere Auto-Mining',
    autoMiningDesc: 'Aktiviere automatisches Mining, das alle 8 Stunden ohne manuellen Eingriff neu startet',
    changeBackground: 'Ändere Hintergrund',
    currentBackground: 'Aktuell',
    free: 'Kostenlos',
    active: 'Aktiv',
    oneTimePurchase: 'Einmaliger Kauf',
    purchaseAutoMining: 'Kaufe Auto-Mining',
    subscriptions: 'Abonnements',
    unlockPremiumFeatures: 'Schalte Premium-Funktionen frei und steigere dein Mining',
    freePlan: 'Kostenlos',
    premiumPlan: 'Premium',
    vipPlan: 'VIP',
    forever: 'Für immer',
    perMonth: 'pro Monat',
    popular: 'Beliebt',
    current: 'Aktuell',
    currentPlan: 'Aktueller Plan',
    selectPlan: 'Wähle Plan',
    subscribe: 'Abonnieren',
    featureComparison: 'Funktionsvergleich',
    customization: 'Anpassung',
    basicMining: 'Basis-Mining',
    standardSpeed: 'Standard-Geschwindigkeit (1x)',
    basicTasks: 'Basis-Aufgaben',
    communitySupport: 'Community-Support',
    fastSpeed: 'Schnelle Geschwindigkeit (5x)',
    premiumTasks: 'Premium-Aufgaben',
    backgroundChange: 'Hintergrund-Anpassung',
    prioritySupport: 'Prioritäts-Support',
    earlyAccess: 'Frühzeitiger Zugriff auf Funktionen',
    ultraFastMining: 'Ultra-schnelles Mining (10x)',
    unlimitedAutoMining: 'Unbegrenztes Auto-Mining',
    exclusiveTasks: 'Exklusive VIP-Aufgaben',
    customBackgrounds: 'Benutzerdefinierte Hintergründe',
    vipSupport: '24/7 VIP-Support',
    specialRewards: 'Spezielle Belohnungen und Boni',
    exclusiveFeatures: 'Exklusive Funktionen',
    exclusiveBackgrounds: 'Exklusive Hintergründe',
    exclusiveBackgroundsDesc: 'Nur für Premium-Mitglieder verfügbare visuelle Themen',
    vipBadge: 'VIP-Abzeichen',
    vipBadgeDesc: 'Zeigen Sie Ihren Premium-Status',
    premiumBenefits: 'Premium-Vorteile',
    bonusPoints: 'Bonuspunkte',
    bonusPointsDesc: '+25% zusätzliche Punkte bei allen Aufgaben',
    subscribeNow: 'Jetzt abonnieren',
    processing: 'Verarbeitung...',
    walletRequired: 'Wallet erforderlich',
    connectWalletFirst: 'Bitte verbinden Sie zuerst Ihre TON-Wallet',
    subscriptionSuccess: 'Abonnement erfolgreich',
    premiumActivated: 'Premium-Plan erfolgreich aktiviert!',
    paymentFailed: 'Zahlung fehlgeschlagen',
    subscriptionError: 'Fehler bei der Verarbeitung der Abonnement-Zahlung',
    completeTasksEarn: 'Erfüllen Sie Aufgaben, um $SPACE-Münzen zu verdienen',
    tasksCompleted: 'Aufgaben erledigt',
    noTasksAvailable: 'Keine Aufgaben verfügbar',
    noTasksDesc: 'Neue Aufgaben werden bald hinzugefügt. Bleiben Sie dran!',
    inviteFriendsEarn: 'Laden Sie Freunde ein und verdienen Sie gemeinsam $SPACE-Münzen',
    totalReferrals: 'Gesamte Empfehlungen',
    totalEarned: 'Gesamt verdient',
    airdropBonus: 'Airdrop-Bonus',
    getReferralLink: 'Empfehlungslink erhalten',
    goToBot: 'Gehen Sie zu',
    onTelegram: 'auf Telegram',
    sendCommand: 'Befehl senden',
    receiveLink: 'Sie erhalten Ihren persönlichen Empfehlungslink',
    openBot: '@Spacelbot öffnen',
    smartWallet: 'Intelligente Wallet',
    walletDescription: 'Sichere und schnelle TON Blockchain Wallet',
    connectWallet: 'Wallet Verbinden',
    connectWalletToAccess: 'Verbinden Sie Ihre Wallet, um auf Funktionen zuzugreifen',
    connecting: 'Verbinden...',
    walletConnected: 'Wallet Verbunden',
    disconnectWallet: 'Trennen',
    mainCurrency: 'Hauptwährung',
    walletAddress: 'Wallet-Adresse',
    latestTransactions: 'Neueste Transaktionen',
    loadingTransactions: 'Transaktionen laden...',
    noTransactions: 'Keine Transaktionen',
    startSendingReceiving: 'Beginnen Sie mit dem Senden und Empfangen von Münzen',
    copied: 'Kopiert!',
    walletAddressCopied: 'Wallet-Adresse kopiert',
    openConnectionWindow: 'Verbindungsfenster öffnen',
    pleaseSelectWallet: 'Bitte wählen Sie Ihre bevorzugte Wallet',
    connectionError: 'Verbindungsfehler',
    failedToOpenWallet: 'Fehler beim Öffnen der Wallet-Verbindung',
    disconnected: 'Getrennt',
    tonWalletDisconnected: 'TON-Wallet wurde getrennt',
    loadingDataError: 'Fehler beim Laden der Daten',
    failedToLoadWallet: 'Fehler beim Laden der Wallet-Daten'
  },
  ja: {
    mining: 'マイニング',
    tasks: 'タスク',
    wallet: 'ウォレット',
    friends: '友達',
    premium: 'プレミアム',
    spaceBalance: '$SPACE 残高',
    miningSpeed: 'マイニング速度',
    timeRemaining: '残り時間',
    startMining: 'マイニング開始',
    stopMining: 'マイニング停止',
    upgradeMiningSpeed: 'マイニング速度をアップグレード',
    fasterMining: 'より速いマイニング',
    autoMining: '自動マイニング',
    autoMiningActive: '自動マイニングアクティブ',
    enableAutoMining: '自動マイニングを有効にする',
    autoMiningDesc: '手動操作なしで8時間ごとに再起動する自動マイニングを有効にします',
    changeBackground: '背景を変更',
    currentBackground: '現在',
    free: '無料',
    active: 'アクティブ',
    oneTimePurchase: '1回限りの購入',
    purchaseAutoMining: '自動マイニングを購入',
    subscriptions: 'サブスクリプション',
    unlockPremiumFeatures: 'プレミアム機能をアンロックしてマイニングをブースト',
    freePlan: '無料プラン',
    premiumPlan: 'プレミアムプラン',
    vipPlan: 'VIPプラン',
    forever: '永久',
    perMonth: '月額',
    popular: '人気',
    current: '現在',
    currentPlan: '現在のプラン',
    selectPlan: 'プランを選択',
    subscribe: 'サブスクライブ',
    featureComparison: '機能比較',
    customization: 'カスタマイズ',
    basicMining: 'ベーシックマイニング',
    standardSpeed: '標準速度 (1x)',
    basicTasks: 'ベーシックタスク',
    communitySupport: 'コミュニティサポート',
    fastSpeed: '高速 (5x)',
    premiumTasks: 'プレミアムタスク',
    backgroundChange: '背景のカスタマイズ',
    prioritySupport: '優先サポート',
    earlyAccess: '機能への早期アクセス',
    ultraFastMining: '超高速マイニング (10x)',
    unlimitedAutoMining: '無制限の自動マイニング',
    exclusiveTasks: '限定VIPタスク',
    customBackgrounds: 'カスタム背景',
    vipSupport: '24時間365日のVIPサポート',
    specialRewards: '特別な報酬とボーナス',
    exclusiveFeatures: '限定機能',
    exclusiveBackgrounds: '限定背景',
    exclusiveBackgroundsDesc: 'プレミアム専用のビジュアルテーマ',
    vipBadge: 'VIPバッジ',
    vipBadgeDesc: 'プレミアムステータスを表示',
    premiumBenefits: 'プレミアム特典',
    bonusPoints: 'ボーナスポイント',
    bonusPointsDesc: '全てのタスクで+25%の追加ポイント',
    subscribeNow: '今すぐ購読',
    processing: '処理中...',
    walletRequired: 'ウォレットが必要',
    connectWalletFirst: '最初にTONウォレットを接続してください',
    subscriptionSuccess: 'サブスクリプション成功',
    premiumActivated: 'プレミアムプランが正常にアクティベートされました！',
    paymentFailed: '支払い失敗',
    subscriptionError: 'サブスクリプション支払いの処理に失敗しました',
    completeTasksEarn: 'タスクを完了して$SPACEコインを獲得',
    tasksCompleted: '完了したタスク',
    noTasksAvailable: '利用可能なタスクなし',
    noTasksDesc: '新しいタスクが間もなく追加されます。お楽しみに！',
    inviteFriendsEarn: '友達を招待して一緒に$SPACEコインを獲得',
    totalReferrals: '総紹介数',
    totalEarned: '総獲得額',
    airdropBonus: 'エアドロップボーナス',
    getReferralLink: '紹介リンクを取得',
    goToBot: '移動',
    onTelegram: 'Telegramで',
    sendCommand: 'コマンドを送信',
    receiveLink: '個人の紹介リンクを受け取ります',
    openBot: '@Spacebotを開く',
    smartWallet: 'スマートウォレット',
    walletDescription: '安全で高速なTONブロックチェーンウォレット',
    connectWallet: 'ウォレット接続',
    connectWalletToAccess: 'ウォレットを接続して機能にアクセス',
    connecting: '接続中...',
    walletConnected: 'ウォレット接続済み',
    disconnectWallet: '切断',
    mainCurrency: 'メイン通貨',
    walletAddress: 'ウォレットアドレス',
    latestTransactions: '最新の取引',
    loadingTransactions: '取引を読み込み中...',
    noTransactions: '取引なし',
    startSendingReceiving: 'コインの送受信を開始',
    copied: 'コピーしました！',
    walletAddressCopied: 'ウォレットアドレスをコピーしました',
    openConnectionWindow: '接続ウィンドウを開いています',
    pleaseSelectWallet: 'お好みのウォレットを選択してください',
    connectionError: '接続エラー',
    failedToOpenWallet: 'ウォレット接続を開けませんでした',
    disconnected: '切断されました',
    tonWalletDisconnected: 'TONウォレットが切断されました',
    loadingDataError: 'データ読み込みエラー',
    failedToLoadWallet: 'ウォレットデータの読み込みに失敗しました'
  },
  tr: {
    mining: 'Madencilik',
    tasks: 'Görevler',
    wallet: 'Cüzdan',
    friends: 'Arkadaşlar',
    premium: 'Premium',
    spaceBalance: '$SPACE Bakiye',
    miningSpeed: 'Madencilik Hızı',
    timeRemaining: 'Kalan Süre',
    startMining: 'Madenciliğe Başla',
    stopMining: 'Madenciliği Durdur',
    upgradeMiningSpeed: 'Madencilik Hızını Yükselt',
    fasterMining: 'daha hızlı madencilik',
    autoMining: 'Otomatik Madencilik',
    autoMiningActive: 'Otomatik Madencilik Aktif',
    enableAutoMining: 'Otomatik Madenciliği Etkinleştir',
    autoMiningDesc: 'Manuel müdahale olmadan her 8 saatte bir yeniden başlayan otomatik madenciliği etkinleştirin',
    changeBackground: 'Arka Planı Değiştir',
    currentBackground: 'Mevcut',
    free: 'Ücretsiz',
    active: 'Aktif',
    oneTimePurchase: 'Tek Seferlik Satın Alma',
    purchaseAutoMining: 'Otomatik Madencilik Satın Al',
    subscriptions: 'Abonelikler',
    unlockPremiumFeatures: 'Premium özellikleri açın ve madenciliğinizi artırın',
    freePlan: 'Ücretsiz Plan',
    premiumPlan: 'Premium Plan',
    vipPlan: 'VIP Plan',
    forever: 'Sonsuza Kadar',
    perMonth: 'aylık',
    popular: 'Popüler',
    current: 'Mevcut',
    currentPlan: 'Mevcut Plan',
    selectPlan: 'Plan Seç',
    subscribe: 'Abone Ol',
    featureComparison: 'Özellik Karşılaştırması',
    customization: 'Özelleştirme',
    basicMining: 'Temel madencilik',
    standardSpeed: 'Standart hız (1x)',
    basicTasks: 'Temel görevler',
    communitySupport: 'Topluluk desteği',
    fastSpeed: 'Hızlı hız (5x)',
    premiumTasks: 'Premium görevler',
    backgroundChange: 'Arka plan özelleştirmesi',
    prioritySupport: 'Öncelikli destek',
    earlyAccess: 'Özelliklere erken erişim',
    ultraFastMining: 'Ultra hızlı madencilik (10x)',
    unlimitedAutoMining: 'Sınırsız otomatik madencilik',
    exclusiveTasks: 'Özel VIP görevleri',
    customBackgrounds: 'Özel arka planlar',
    vipSupport: '7/24 VIP desteği',
    specialRewards: 'Özel ödüller ve bonuslar',
    exclusiveFeatures: 'Özel özellikler',
    exclusiveBackgrounds: 'Özel arka planlar',
    exclusiveBackgroundsDesc: 'Sadece premium için görsel temalar',
    vipBadge: 'VIP Rozeti',
    vipBadgeDesc: 'Premium durumunuzu gösterin',
    premiumBenefits: 'Premium Avantajları',
    bonusPoints: 'Bonus Puanları',
    bonusPointsDesc: 'Tüm görevlerde +%25 ekstra puan',
    subscribeNow: 'Şimdi Abone Ol',
    processing: 'İşleniyor...',
    walletRequired: 'Cüzdan Gerekli',
    connectWalletFirst: 'Lütfen önce TON cüzdanınızı bağlayın',
    subscriptionSuccess: 'Abonelik Başarılı',
    premiumActivated: 'Premium plan başarıyla etkinleştirildi!',
    paymentFailed: 'Ödeme Başarısız',
    subscriptionError: 'Abonelik ödemesi işlenemedi',
    completeTasksEarn: '$SPACE coin kazanmak için görevleri tamamlayın',
    tasksCompleted: 'Tamamlanan Görevler',
    noTasksAvailable: 'Mevcut Görev Yok',
    noTasksDesc: 'Yeni görevler yakında eklenecek. Takipte kalın!',
    inviteFriendsEarn: 'Arkadaşları davet edin ve birlikte $SPACE coin kazanın',
    totalReferrals: 'Toplam Yönlendirmeler',
    totalEarned: 'Toplam Kazanılan',
    airdropBonus: 'Airdrop Bonusu',
    getReferralLink: 'Yönlendirme Bağlantısı Al',
    goToBot: 'Git',
    onTelegram: 'Telegram\'da',
    sendCommand: 'Komutu gönder',
    receiveLink: 'Kişisel yönlendirme bağlantınızı alacaksınız',
    openBot: '@Spacelbot\'u aç',
    smartWallet: 'Akıllı Cüzdan',
    walletDescription: 'Güvenli ve Hızlı TON Blockchain Cüzdanı',
    connectWallet: 'Cüzdan Bağla',
    connectWalletToAccess: 'Özelliklere erişmek için cüzdanınızı bağlayın',
    connecting: 'Bağlanıyor...',
    walletConnected: 'Cüzdan Bağlandı',
    disconnectWallet: 'Bağlantıyı Kes',
    mainCurrency: 'Ana Para Birimi',
    walletAddress: 'Cüzdan Adresi',
    latestTransactions: 'Son İşlemler',
    loadingTransactions: 'İşlemler yükleniyor...',
    noTransactions: 'İşlem Yok',
    startSendingReceiving: 'Para gönderme ve alma işlemlerine başlayın',
    copied: 'Kopyalandı!',
    walletAddressCopied: 'Cüzdan adresi kopyalandı',
    openConnectionWindow: 'Bağlantı penceresi açılıyor',
    pleaseSelectWallet: 'Lütfen tercih ettiğiniz cüzdanı seçin',
    connectionError: 'Bağlantı Hatası',
    failedToOpenWallet: 'Cüzdan bağlantısı açılamadı',
    disconnected: 'Bağlantı Kesildi',
    tonWalletDisconnected: 'TON cüzdanının bağlantısı kesildi',
    loadingDataError: 'Veri Yükleme Hatası',
    failedToLoadWallet: 'Cüzdan verilerini yükleyemedi'
  },
  pt: {
    mining: 'Mineração',
    tasks: 'Tarefas',
    wallet: 'Carteira',
    friends: 'Amigos',
    premium: 'Premium',
    spaceBalance: 'Saldo $SPACE',
    miningSpeed: 'Velocidade de Mineração',
    timeRemaining: 'Tempo Restante',
    startMining: 'Começar a Minerar',
    stopMining: 'Parar de Minerar',
    upgradeMiningSpeed: 'Aumentar a Velocidade de Mineração',
    fasterMining: 'mineração mais rápida',
    autoMining: 'Mineração Automática',
    autoMiningActive: 'Mineração Automática Ativa',
    enableAutoMining: 'Ativar Mineração Automática',
    autoMiningDesc: 'Ative a mineração automática que reinicia a cada 8 horas sem intervenção manual',
    changeBackground: 'Mudar o Fundo',
    currentBackground: 'Atual',
    free: 'Grátis',
    active: 'Ativo',
    oneTimePurchase: 'Compra Única',
    purchaseAutoMining: 'Comprar Mineração Automática',
    subscriptions: 'Assinaturas',
    unlockPremiumFeatures: 'Desbloqueie recursos premium e impulsione sua mineração',
    freePlan: 'Grátis',
    premiumPlan: 'Premium',
    vipPlan: 'VIP',
    forever: 'Para sempre',
    perMonth: 'por mês',
    popular: 'Popular',
    current: 'Atual',
    currentPlan: 'Plano Atual',
    selectPlan: 'Selecionar Plano',
    subscribe: 'Assinar',
    featureComparison: 'Comparação de Recursos',
    customization: 'Customização',
    basicMining: 'Mineração Básica',
    standardSpeed: 'Velocidade Padrão (1x)',
    basicTasks: 'Tarefas Básicas',
    communitySupport: 'Suporte da Comunidade',
    fastSpeed: 'Velocidade Rápida (5x)',
    premiumTasks: 'Tarefas Premium',
    backgroundChange: 'Customização de Fundo',
    prioritySupport: 'Suporte Prioritário',
    earlyAccess: 'Acesso Antecipado a Recursos',
    ultraFastMining: 'Mineração Ultra-Rápida (10x)',
    unlimitedAutoMining: 'Mineração Automática Ilimitada',
    exclusiveTasks: 'Tarefas VIP Exclusivas',
    customBackgrounds: 'Fundos Customizados',
    vipSupport: 'Suporte VIP 24/7',
    specialRewards: 'Recompensas e Bônus Especiais',
    exclusiveFeatures: 'Recursos Exclusivos',
    exclusiveBackgrounds: 'Fundos exclusivos',
    exclusiveBackgroundsDesc: 'Temas visuais exclusivos para premium',
    vipBadge: 'Distintivo VIP',
    vipBadgeDesc: 'Mostre seu status premium',
    premiumBenefits: 'Benefícios Premium',
    bonusPoints: 'Pontos Bônus',
    bonusPointsDesc: '+25% pontos extras em todas as tarefas',
    subscribeNow: 'Assinar Agora',
    processing: 'Processando...',
    walletRequired: 'Carteira Necessária',
    connectWalletFirst: 'Por favor, conecte sua carteira TON primeiro',
    subscriptionSuccess: 'Assinatura Bem-sucedida',
    premiumActivated: 'Plano premium ativado com sucesso!',
    paymentFailed: 'Pagamento Falhou',
    subscriptionError: 'Falha ao processar pagamento da assinatura',
    completeTasksEarn: 'Complete tarefas para ganhar moedas $SPACE',
    tasksCompleted: 'Tarefas Concluídas',
    noTasksAvailable: 'Nenhuma Tarefa Disponível',
    noTasksDesc: 'Novas tarefas serão adicionadas em breve. Fique ligado!',
    inviteFriendsEarn: 'Convide amigos e ganhem moedas $SPACE juntos',
    totalReferrals: 'Total de Indicações',
    totalEarned: 'Total Ganho',
    airdropBonus: 'Bônus de Airdrop',
    getReferralLink: 'Obter Link de Indicação',
    goToBot: 'Ir para',
    onTelegram: 'no Telegram',
    sendCommand: 'Enviar o comando',
    receiveLink: 'Você receberá seu link de indicação pessoal',
    openBot: 'Abrir @Spacelbot',
    smartWallet: 'Carteira Inteligente',
    walletDescription: 'Carteira TON Segura e Rápida',
    connectWallet: 'Conectar Carteira',
    connectWalletToAccess: 'Conecte sua carteira para acessar os recursos',
    connecting: 'Conectando...',
    walletConnected: 'Carteira Conectada',
    disconnectWallet: 'Desconectar',
    mainCurrency: 'Moeda Principal',
    walletAddress: 'Endereço da Carteira',
    latestTransactions: 'Transações Recentes',
    loadingTransactions: 'Carregando transações...',
    noTransactions: 'Sem Transações',
    startSendingReceiving: 'Comece a enviar e receber moedas',
    copied: 'Copiado!',
    walletAddressCopied: 'Endereço da carteira copiado',
    openConnectionWindow: 'Abrindo janela de conexão',
    pleaseSelectWallet: 'Por favor, selecione sua carteira preferida',
    connectionError: 'Erro de Conexão',
    failedToOpenWallet: 'Falha ao abrir conexão da carteira',
    disconnected: 'Desconectado',
    tonWalletDisconnected: 'Carteira TON foi desconectada',
    loadingDataError: 'Erro ao Carregar Dados',
    failedToLoadWallet: 'Falha ao carregar dados da carteira'
  },
  uk: {
    mining: 'Майнінг',
    tasks: 'Завдання',
    wallet: 'Гаманець',
    friends: 'Друзі',
    premium: 'Преміум',
    spaceBalance: 'Баланс $SPACE',
    miningSpeed: 'Швидкість майнінгу',
    timeRemaining: 'Залишок часу',
    startMining: 'Почати майнінг',
    stopMining: 'Зупинити майнінг',
    upgradeMiningSpeed: 'Покращити швидкість майнінгу',
    fasterMining: 'швидший майнінг',
    autoMining: 'Автоматичний майнінг',
    autoMiningActive: 'Автоматичний майнінг активний',
    enableAutoMining: 'Увімкнути автоматичний майнінг',
    autoMiningDesc: 'Увімкніть автоматичний майнінг, який перезапускається кожні 8 годин без ручного втручання',
    changeBackground: 'Змінити фон',
    currentBackground: 'Поточний',
    free: 'Безкоштовно',
    active: 'Активний',
    oneTimePurchase: 'Одноразова покупка',
    purchaseAutoMining: 'Придбати автоматичний майнінг',
    subscriptions: 'Підписки',
    unlockPremiumFeatures: 'Розблокуйте преміум-функції та збільште свій майнінг',
    freePlan: 'Безкоштовний',
    premiumPlan: 'Преміум',
    vipPlan: 'VIP',
    forever: 'Назавжди',
    perMonth: 'на місяць',
    popular: 'Популярний',
    current: 'Поточний',
    currentPlan: 'Поточний план',
    selectPlan: 'Вибрати план',
    subscribe: 'Підписатися',
    featureComparison: 'Порівняння функцій',
    customization: 'Налаштування',
    basicMining: 'Базовий майнінг',
    standardSpeed: 'Стандартна швидкість (1x)',
    basicTasks: 'Базові завдання',
    communitySupport: 'Підтримка спільноти',
    fastSpeed: 'Швидка швидкість (5x)',
    premiumTasks: 'Преміум завдання',
    backgroundChange: 'Налаштування фону',
    prioritySupport: 'Пріоритетна підтримка',
    earlyAccess: 'Ранній доступ до функцій',
    ultraFastMining: 'Ультра-швидкий майнінг (10x)',
    unlimitedAutoMining: 'Необмежений автоматичний майнінг',
    exclusiveTasks: 'Ексклюзивні VIP завдання',
    customBackgrounds: 'Користувацькі фони',
    vipSupport: 'Цілодобова VIP підтримка',
    specialRewards: 'Спеціальні нагороди та бонуси',
    exclusiveFeatures: 'Ексклюзивні функції',
    exclusiveBackgrounds: 'Ексклюзивні фони',
    exclusiveBackgroundsDesc: 'Візуальні теми тільки для преміум',
    vipBadge: 'VIP значок',
    vipBadgeDesc: 'Покажіть свій преміум статус',
    premiumBenefits: 'Переваги Преміум',
    bonusPoints: 'Бонусні бали',
    bonusPointsDesc: '+25% додаткових балів за всі завдання',
    subscribeNow: 'Підписатися зараз',
    processing: 'Обробка...',
    walletRequired: 'Потрібен гаманець',
    connectWalletFirst: 'Будь ласка, спочатку підключіть свій гаманець TON',
    subscriptionSuccess: 'Підписка успішна',
    premiumActivated: 'Преміум план успішно активовано!',
    paymentFailed: 'Платіж не вдався',
    subscriptionError: 'Не вдалося обробити платіж підписки',
    completeTasksEarn: 'Виконуйте завдання, щоб заробити монети $SPACE',
    tasksCompleted: 'Завдання виконано',
    noTasksAvailable: 'Немає доступних завдань',
    noTasksDesc: 'Нові завдання будуть додані незабаром. Слідкуйте за оновленнями!',
    inviteFriendsEarn: 'Запрошуйте друзів і заробляйте монети $SPACE разом',
    totalReferrals: 'Загальна кількість рефералів',
    totalEarned: 'Загальний заробіток',
    airdropBonus: 'Бонус аірдропу',
    getReferralLink: 'Отримати реферальне посилання',
    goToBot: 'Перейти до',
    onTelegram: 'в Telegram',
    sendCommand: 'Надіслати команду',
    receiveLink: 'Ви отримаєте своє персональне реферальне посилання',
    openBot: 'Відкрити @Spacelbot',
    smartWallet: 'Розумний гаманець',
    walletDescription: 'Безпечний та швидкий гаманець TON',
    connectWallet: 'Підключити гаманець',
    connectWalletToAccess: 'Підключіть гаманець для доступу до функцій',
    connecting: 'Підключення...',
    walletConnected: 'Гаманець підключено',
    disconnectWallet: 'Відключити',
    mainCurrency: 'Основна валюта',
    walletAddress: 'Адреса гаманця',
    latestTransactions: 'Останні транзакції',
    loadingTransactions: 'Завантаження транзакцій...',
    noTransactions: 'Немає транзакцій',
    startSendingReceiving: 'Почніть відправляти та отримувати монети',
    copied: 'Скопійовано!',
    walletAddressCopied: 'Адреса гаманця скопійована',
    openConnectionWindow: 'Відкриття вікна підключення',
    pleaseSelectWallet: 'Будь ласка, оберіть ваш улюблений гаманець',
    connectionError: 'Помилка підключення',
    failedToOpenWallet: 'Не вдалося відкрити підключення гаманця',
    disconnected: 'Відключено',
    tonWalletDisconnected: 'Гаманець TON відключено',
    loadingDataError: 'Помилка завантаження даних',
    failedToLoadWallet: 'Не вдалося завантажити дані гаманця'
  },
};

export const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem('selectedLanguage');
  if (stored) {
    const parsed = JSON.parse(stored);
    return languages.find(lang => lang.code === parsed.code) || languages[0];
  }
  return languages[0];
};

export const setStoredLanguage = (language: Language): void => {
  localStorage.setItem('selectedLanguage', JSON.stringify(language));
};

export const getTranslation = (key: string, languageCode: string): string => {
  return translations[languageCode]?.[key] || translations.en[key] || key;
};
