// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axeaidkkxgpgrmnmkfzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZWFpZGtreGdwZ3Jtbm1rZnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTU4NjIsImV4cCI6MjA2MzM5MTg2Mn0.38zcnA6NMawBYyoWal_3Ai8R30g_nniAaNKiAYGJAJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);