// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozjhsilgajjubeomlig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvempoc2lsZ2FqanViZW9tbGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDgzMDYsImV4cCI6MjA2NDUyNDMwNn0.ClwBaDS4NdS4sYy5oA3SdK6Dwi__ugeJDKZIun-P_B4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);