// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opzimlmthgbehciattkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wemltbG10aGdiZWhjaWF0dGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTIxMTIsImV4cCI6MjA2Mzg4ODExMn0.8hVOghmzxwrs7_AhrLLLLuRsXh1fXltdoTgBO3ZVBI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);